### ISSUE TITLE
Bring back dimming nav in conversation view

### ISSUE THREAD

**Issue by jason-mehmel** [leggett/simplify#594] opened 2021-06-13 05:21 UTC
I've got two instances of gmail. One is my regular [at]gmail.com account, and the other is a Google Suite for Not For Profits that's associated with our web domain.

Simplify features don't seem to appear on the Google Suite gmail version... the dimming of the labels and buttons on the right is the one I've noticed so far. (I feel like there are others but I can't find them right now! I'll add to this post if I can find them again.)

**Comment by leggett** [comment] 2021-06-13 14:40
Thanks for the report. I'm not sure what you mean by "the dimming of labels and buttons on the right." The labels are on the left... unless you are using a right-to-left language (which Simplify doesn't currently support).

Simplify is supposed to be the same for consumer accounts and Workspace accounts. That said, Gmail itself is different between the two and sometimes [things break](https://github.com/leggett/simplify/issues/591) for just one or the other.

To troubleshoot further, here are two things that would help:

- A system report (details on how to attach that at the bottom of [simpl.fyi/support](https://simpl.fyi/support)).
- Screenshots and/or steps to reproduce a problem

**Comment by jason-mehmel** [comment] 2021-06-13 18:20
That was my mistake! The labels and buttons are on the left. I was hopping between emails while submitting.

I will do a system report and work on the screenshots!

**Comment by leggett** [comment] 2021-06-13 18:32
Got it. The labels and buttons on the left don't dim any more when you open a conversation (they haven't for a long time). What browser are you using? You might need to accept the new permissions to get the latest version (v2.4.1)

Details on the new permissions here: https://on.simpl.fyi/p/v233-new-permissions

**Comment by jason-mehmel** [comment] 2021-06-14 00:59
I'm using Firefox!

The version in my extension is 2.4.1

On my normal gmail, the stuff on the left (inbox, starred, snoozed, spam, bin, plus the labels, etc) dim when I enter a conversation. They don't when I'm in my Google Suite account.

(If this is useful, I'm logged into both in my browser at the same time, using the multi-account feature in Google.)

The other difference I discovered was the option of removing the 'importance' flags on the messages. When I turned on that feature, it worked for the 'regular' gmail but not the google suite.

In terms of system reports, should I just click that option on both accounts and submit?

**Comment by leggett** [comment] 2021-06-14 01:05
Thanks for the details. I'll look into it.

One system report tells me all I need. You are on the latest version of
Simplify with Firefox, so it is probably a bug on my end.

**Comment by jason-mehmel** [comment] 2021-06-14 01:12
Awesome. I did the system report via Forms, so as not to confuse the github posts!

I'll do screenshots soon when things are little less busy and I have time to blur the personal details!

**Comment by leggett** [comment] 2021-06-14 02:58
System report: Simplify v.2.4.1 - Configuration: aAX appMenuOpen ca3 caI caL cfC cfO cfQ cfR cfU composeFormat darkTheme debug hideMsgCount hideSelectRefresh hideTabIcons highDensity inInbox inList invertAddons invertCompose izBgDefault listWidthLg matchFontSize minimizeChat msgLabelsRight msgWidthSm navOpen oeBoomerang otherExtensions sendLater simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (X11 Ubuntu Linux x86_64 rv:89.0) Gecko/20100101 Firefox/89.0 - Window: 1333 x 750 (100pct zoom) - Language: en-GB

**Comment by leggett** [comment] 2021-06-14 03:03
**Dimming left nav**
I found the issue with the dimming left nav -- I thought I removed that but I just removed it for Gmail's new nav (which I have on most my accounts). I'll look into bringing that back. 

**Importance indicator**
I don't actually do anything with importance indicators since you can turn them off under Gmail Settings > Inbox > Importance markers. Are you saying that you can't disable them for your Workspace account?

**Comment by jason-mehmel** [comment] 2021-06-14 03:13
**Dimming left nav**

The new nav comment is interesting: I think I've got the new nav on my Workspace account but not my regular gmail. So it was actually working properly in the workspace!

So it sounds like that's an element that you actually removed? I do like it... any chance it could be remain as an option?

**Importance indicator**
/facepalm/ That was a gmail setting, not yours. Apologies.

**Comment by leggett** [comment] 2021-06-14 03:22
Yeah, I'll probably bring back the dimming. I need to look into it and try to remember why I thought I stopped doing it. Maybe I got feedback that made me think it was a bad idea. I'm not sure.

**Comment by leggett** [comment] 2021-08-22 19:22
This was fixed in v2.4.2. Let me know if you still see any issues.

**Closed by leggett** 2021-08-22 19:22 UTC
