### ISSUE TITLE
Dark Theme - new email compose window flashes white

### ISSUE THREAD

**Issue by mrtrevelyan** [leggett/simplify#625] opened 2021-11-08 06:24 UTC
Please describe the issue and the steps to reproduce it. Screenshots are useful.

Hi - I'm using the dark theme setting and have dark theme windows turned on in the settings - when I'm composing a new email (when I press the + button), the new email window blinks black and white (attached is a partial new email compose window as it flashes white - it should be dark all the time).

This started happening around two weeks ago. None of the other windows (inbox panel, main email pane) have this flashing white issue - just the new email window

Hopefully you're able to solve the issue as the flashing is quite distracting!

---
Simplify v.2.5.4 - Configuration: aAX ca5 caC caD caI caL cfC cfO cfQ cfR cfU composeActions darkTheme dateGroup fontMsg hideEmptySections hideListCount hideMsgCount hideTabIcons inInbox inList invertAddons invertCompose izBg2 listWidthLg lowDensity minimizeChat msgOpen msgWidthSm simplify supExtWarn vPane - System: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 - Window: 1440 x 875 (100pct zoom) - Language: e
<img width="596" alt="Screen Shot 2021-11-07 at 10 18 21 PM" src="https://user-images.githubusercontent.com/5968648/140693572-ecfb8e3c-1edb-417c-a799-bc1b6e21e785.png">
n

**Comment by leggett** [comment] 2021-11-08 06:30
The flickering is a new issue I haven't been able to reproduce thus far but you're not the first to report the issue. I had a video call with one person to try and figure out what is going on and wasn't able to find the source of the issue. The area that flickers doesn't align with any of the elements as far as I can tell.

I recommend disabling "Make compose dark" in Simplify's settings until I figure it out. I'll update this issue once I figure out the issue so you can turn it back on.

**Comment by mrtrevelyan** [comment] 2021-11-08 06:48
Ah I think maybe I'm onto something: the new compose window seems to flash white when:

- behind that window is an open email in the right hand reading pane (I'm using vertical split view), AND
-  that open email has an image in it!

When I open a new compose window with a text only email behind it on the reading pane (or no open email window at all in the reading pane), the new compose window doesn't flash white.

FYI - I also have a wallpaper background  that shows when there are no emails in the reading pane.

So maybe it has something to do with the dark theme not liking the overlap over an image? (screenshot below showing part of the new compose window as it flashes white in the situation described above)

<img width="970" alt="Screen Shot 2021-11-07 at 10 45 37 PM" src="https://user-images.githubusercontent.com/5968648/140696138-3609af85-9bbf-41ec-8f01-4ba667b3c9c3.png">

**Comment by leggett** [comment] 2021-11-08 06:56
Thanks for trying to help find steps to reproduce the issue. Unfortunately, it doesn't flicker for me in this setup either.

Is your entire compose window flickering? The user that I spoke with on a video call had an odd sub-area of the composer (not aligned with any DOM elements) flickering.

**Comment by leggett** [comment] 2021-11-08 15:00
Do you have any other extensions installed that have access to Gmail? Like Dark Reader?

**Comment by mrtrevelyan** [comment] 2021-11-08 15:29
Yes I do have dark reader - but I turn it off for mail.google.com (I also
thought maybe it was that extension, so I've also tried toggling it off
completely, as well as trying turning dark reader on and setting it to
Light mode, but neither works to stop the flickering. I can see why that
might cause an issue though (but I've had dark reader for longer than I've
had Simplify, and up until these past couple of weeks, both Simplify and
Dark Reader played nice with each other (but yes DR is off for gmail!)

**Comment by leggett** [comment] 2021-11-21 17:39
I finally got this on my own account and was able to figure out the cause and a fix. It will go out in the next couple days in v2.5.6. I will update and close this issue when it is out to everyone.

**Comment by mrtrevelyan** [comment] 2021-11-21 17:52
Brilliant thanks Michael!

**Comment by leggett** [comment] 2021-11-21 18:49
Update is live for canary.simpl.fyi and firefox.simpl.fyi and at 5% for chrome.simpl.fyi

**Closed as completed by leggett** 2021-11-21 18:49 UTC
