### ISSUE TITLE
Overlapping icon layout in top right-hand corner

### ISSUE THREAD

**Issue by benjaminsfrank** [leggett/simplify#289] opened 2020-07-02 23:28 UTC
Firefox 77 on Mac
Screen is 1440px wide

Seeing 3 layout things in the top right-hand corner which seem related:

1. "Select Input Tools" button and part of "Input tools on/off" button is behind (?) the account switcher.
<img width="328" alt="Screen Shot 2020-07-02 at 7 22 01 PM" src="https://user-images.githubusercontent.com/714472/86416921-fc3cbf80-bcba-11ea-9257-aaf4463917a2.png">

2. Search button is overlapping with the Previous/Next buttons and can't be hovered/clicked.
<img width="235" alt="Screen Shot 2020-07-02 at 7 22 47 PM" src="https://user-images.githubusercontent.com/714472/86416923-fe068300-bcba-11ea-90ad-92c53264a84f.png">
and 
<img width="243" alt="Screen Shot 2020-07-02 at 7 28 03 PM" src="https://user-images.githubusercontent.com/714472/86417161-b7655880-bcbb-11ea-9582-b5de9199990e.png">

3. Help and Settings buttons can't be hovered/clicked.

**Comment by leggett** [comment] 2020-07-03 01:24
Oof. That's super bad. It looks like it isn't properly hiding the company logo in the top right and thereby pushing things over. 

I'm not seeing this on my end though (testing in Firefox 78 on Mac with Simplify v1.7.16).

Can you try doing a hard refresh (Shift + Click on refresh) to see if that fixes it?

**Comment by leggett** [comment] 2020-07-03 17:11
I'm going to close this for now since I can't reproduce the issue. Please re-open if you are still seeing it after a hard refresh.

**Closed by leggett** 2020-07-03 17:11 UTC

**Comment by benjaminsfrank** [comment] 2020-07-06 18:57
Looks like a couple hard refreshes fixed it. Thanks for the quick reply!

**Comment by benjaminsfrank** [comment] 2020-07-07 21:52
Seeing one more where the search filter pill buttons overlap the "Did you mean?" bar below. Is this the right place for it, or should be a separate issue?

![Screen Shot 2020-07-07 at 5 49 03 PM](https://user-images.githubusercontent.com/714472/86847458-e30d8780-c09b-11ea-939a-ad3661578c84.png)

**Comment by leggett** [comment] 2020-07-08 16:20
Thanks @benjaminsfrank -- I created a new issue to track that as it is a different part of Simplify.
