### ISSUE TITLE
Support add-ons chooser with more than 3 add-ons at top level.

### ISSUE THREAD

**Issue by rpartha** [leggett/simplify#34] opened 2019-04-08 13:42 UTC
![image](https://user-images.githubusercontent.com/3248921/55728665-8461e580-59e2-11e9-8121-7d9f2c3deddc.png)

It appears to be invisible underneath the tasks button in the fab (where I highlighted), not that I use additional add-ons anyways.

**Comment by leggett** [comment] 2019-04-08 19:07
Ah... when I tested it, all the add-ons were below an overflow menu. Looks like you have one at the top level. I didn't realize that was possible. What is the add-on (the yellow rectangle)?

**Comment by rpartha** [comment] 2019-04-08 19:19
The yellow rectangle is supposed to be the button to get more add-ons. It's currently invisible.

**Comment by leggett** [comment] 2019-04-08 19:25
Ah, it is visible for me. So I'll need to look into it more. Maybe because you are using a theme.
<img width="124" alt="Screen Shot 2019-04-08 at 12 24 33 PM" src="https://user-images.githubusercontent.com/8763662/55750957-58059380-59f9-11e9-85b7-1ba0a302ef58.png">

**Comment by rpartha** [comment] 2019-04-09 15:50
Ah ok. Thanks for the quick fix.

**Comment by leggett** [comment] 2019-04-09 17:16
Fixed in v1.1.1 last night or maybe it was in v1.1.2 that just went live. Either way, it is fixed.

**Comment by leggett** [comment] 2019-04-10 16:53
This is still broken in some instances resulting in no icon being in the minimized FAB.

**Comment by rpartha** [comment] 2019-04-10 16:58
I noticed it but didn't bring it up as it didn't bother me much.

**Comment by mightymouse2045** [comment] 2019-04-16 15:05
Cool yeah I don't have the add-on chooser showing with or without a theme selected. Can the add-on area be made scrollable perhaps if the person has a large number of add-ons?:
Theme
![image](https://user-images.githubusercontent.com/878160/56220665-6576e980-609b-11e9-9b8f-24c028cee633.png)

No Theme
![image](https://user-images.githubusercontent.com/878160/56220693-71fb4200-609b-11e9-9441-6f2351296120.png)

**Comment by leggett** [comment] 2019-04-16 16:54
You mean the button to get more add-ons? If so, you can get to that under the gear menu in the top right of Gmail. I could look at bringing back the plus button inside the adds-ons menu too.

**Comment by mightymouse2045** [comment] 2019-04-16 17:17
Yes I just noticed that. That's fine if it lives elsewhere. But any more
than 4 add-ons don't display when hovering on the add-ons...

**Comment by leggett** [comment] 2019-04-16 17:31
It should show as many as you have. There are 5 in the above screenshot. I just added a bunch to my test account and they all show up. You might have to refresh after adding some. 

<img width="127" alt="Screen Shot 2019-04-16 at 10 30 37 AM" src="https://user-images.githubusercontent.com/8763662/56231221-ce764700-6032-11e9-96c8-c9748634fc8e.png">

Are you saying that Gmail itself hides them somewhere if you have more and they aren't showing up with Simplify enabled?

**Comment by leggett** [comment] 2019-04-16 17:56
Re-open this if I'm missing something.

**Closed by leggett** 2019-04-16 17:56 UTC
Labels: bug

**Comment by mightymouse2045** [comment] 2019-04-17 03:36
Thanks you are totally correct - it required a refresh - I'm good with this staying closed :P

**Comment by visiba** [comment] 2019-04-18 08:02
Seems to have broken the FAB here...
![18-04-2019 10-02-05](https://user-images.githubusercontent.com/7481704/56345897-19be6000-61c1-11e9-8370-b718cbf3feb5.png)

**Comment by mightymouse2045** [comment] 2019-04-18 08:05
I just noticed this. Also there is a problem in the search since you fixed
the other change.

After doing an advanced search it doesn't 'clear' properly with the X

Can you reproduce that as well?

**Comment by leggett** [comment] 2019-04-18 14:03
I found the issue with the add-ons and will submit a fix shortly.

And can reproduce the advanced search bug. Have a fix for that now too. 

Both will be fixed in v1.1.9.

**Comment by mightymouse2045** [comment] 2019-04-18 15:18
Legend thanks :) Lol I am still stuck on reducing the padding and sorting
out the nav background issue myself :P
