### ISSUE TITLE
Extra Compose Button - FlowCrypt

### ISSUE THREAD

**Issue by sergiomoraes** [leggett/simplify#427] opened 2020-11-22 17:41 UTC
Currently, the [FlowCrytp](https://flowcrypt.com/) app adds a new Compose button to the UI that allows for writing PGP signed and/or encrypted emails.

This is how it looks like:
![flow_crypt_compose](https://user-images.githubusercontent.com/21162065/99911009-64aa2e80-2ca6-11eb-8bff-ad3a6db1811b.png)

With the understanding that Simplify Gmail can't accommodate all the different extensions out there, I was wondering if I could get some guidance on how to get this button to show up by modifying code on my end. Perhaps using something like [Stylus](https://add0n.com/stylus.html).

**Comment by leggett** [comment] 2020-11-22 18:13
I hope to add minimal support for the most popular Gmail extensions. I've never heard of FlowCrypt but it appears to have a large install base. Is the only thing that doesn't work this compose button?

It depends on how the other extension added their button. It might still be visible at the top of your nav with Simplify enabled. Moving it along with Gmail's compose button is somewhat complex as it needs to move to different places depending on if quick settings are open, add-ons are open, right-side chat is open, or vertical split pane is enabled.

**Comment by sergiomoraes** [comment] 2020-11-22 19:29
That's correct. If I disable Simplify, click the FlowCrypt button and re-enable Simplify, everything continues to work fine.


It looks like it's following Gmail's Compose button but once I turn on Simplify, it becomes hidden (as if it was behind the Gmail button).


This is what I see inspecting the page:


![flow_crypt_compose_html-css](https://user-images.githubusercontent.com/21162065/99915017-f53c3b00-2cb5-11eb-9b04-8cc1d08dcf43.png)

**Comment by leggett** [comment] 2020-11-22 20:02
Yeah, the problem is .z0 was a unique classname for the Gmail compose button. So I suspect it is actually *under* the Gmail compose button in the bottom right corner. 

If you add the following css via Stylus, it should fix it:

`
.firefoxcryptupio_destroyable.z0 {
  transform: translateY(-64px);
}
`

**Closed by leggett** 2020-11-22 20:02 UTC

**Comment by leggett** [comment] 2021-02-05 07:24
FYI: I'm adding proper support for this with Simplify v2. I wouldn't have done that if you hadn't filed the request. So on behalf of anyone using both Simplify and Flowcrypt, thanks!

**Comment by sergiomoraes** [comment] 2021-02-06 01:53
Thank you very much @leggett. I'm beyond excited for Simplify v2!
