### ISSUE TITLE
Email navigation bar not working

### ISSUE THREAD

**Issue by cloudconceptsau** [leggett/simplify#497] opened 2021-02-08 18:45 UTC
I can't use the arrow buttons to move from one email to the next when I'm viewing an email nor can I refresh my inbox as no clicks are registering on these icons

**Comment by leggett** [comment] 2021-02-08 18:50
Thanks for the report! This is happening for some people that use other extensions along side Simplify. I have a fix going in today for "Inbox When Ready". 

If you don't use other extensions or want me to look at your case, can you use the "Report issue" button so I can get a little more context? 

<img width="258" alt="Screen Shot 2021-02-08 at 10 48 41 AM" src="https://user-images.githubusercontent.com/8763662/107267176-6230b880-69fb-11eb-8518-23cc0b0de7ee.png">

**Comment by leggett** [comment] 2021-02-14 22:13
I'm going to close this as I think it was a conflict with another extension and that has been fixed. But please re-open if the issue is still happening for you.

**Closed by leggett** 2021-02-14 22:13 UTC
