### ISSUE TITLE
The new Filter buttons break the layout when preview pane is enabled

### ISSUE THREAD

**Issue by pronouncedJerry** [leggett/simplify#255] opened 2020-02-27 15:05 UTC
Hey Michael,

Thank you for this extension, it vastly improves the Gmail UX. Just a heads up that the [new filter buttons](https://techcrunch.com/2020/02/19/gmail-finally-makes-easier-to-search-your-email/) prevent me from accessing the first email in the list after running a search.

**Comment by leggett** [comment] 2020-02-27 15:35
Thanks for the report! 

I see it overlaps a tiny bit and I will fix, but it sounds like it is a lot worse for you. Can you post or email me (hi@simpl.fyi) a screenshot so I can see your setup and better diagnose the problem?

**Comment by leggett** [comment] 2020-03-03 20:36
Jerry sent a screenshot -- the issue is when preview pane is enabled.

**Comment by pronouncedJerry** [comment] 2020-03-05 23:44
yup, the buttons overlay on the first row of emails

**Comment by jaketame** [comment] 2020-03-11 18:27
Also experiencing this issue.

**Comment by leggett** [comment] 2020-04-20 19:23
I've got a fix for this now. I'll submit to Firefox now and Chrome after using it for 24 hours to make sure there aren't any issues.

**Closed** 2020-04-20 19:25 UTC
Labels: bug

**Comment by Julian88Tex** [comment] 2020-04-22 06:40
@leggett works for me now thanks!
