### ISSUE TITLE
Google Tasks bottom padding is a little off. 

### ISSUE THREAD

**Issue by simoncla** [leggett/simplify#35] opened 2019-04-08 15:38 UTC
![image](https://user-images.githubusercontent.com/1838429/55737263-c27bfb00-5a1c-11e9-9212-bc8a28dc7dd3.png)

Just a little off.

**Comment by leggett** [comment] 2019-04-08 16:57
Thanks. Figured out the cause and will be fixed in the next release (v1.1.1.)

**Closed by leggett** 2019-04-08 16:57 UTC
