### ISSUE TITLE
Buttons in wrong place with Multiple Inboxes

### ISSUE THREAD

**Issue by Queuecumber** [leggett/simplify#84] opened 2019-04-25 18:42 UTC
I use two gmail accounts, a personal one and a gapps one for work. On my personal account, at the inbox panel, the action buttons don't seem to be placed correctly. Weirdly though they are placed the same on my gapps account. Also when I open an email, those action buttons look like they are in the right place regardless of what account I use. Attached images to illustrate

## My Personal GMail Inbox (wrong spot)

![Screenshot from 2019-04-25 14-32-27](https://user-images.githubusercontent.com/5865387/56760029-45fd5200-6768-11e9-9cff-a0ba03e28a79.png)

## Opening an email (right spot)

![Screenshot from 2019-04-25 14-32-34](https://user-images.githubusercontent.com/5865387/56759904-0171b680-6768-11e9-8266-89a5f462b147.png)

## Inbox on GApps (right spot)

![Screenshot from 2019-04-25 14-32-30](https://user-images.githubusercontent.com/5865387/56759929-12bac300-6768-11e9-9f27-9b8f7234de2e.png)

**Comment by leggett** [comment] 2019-04-25 19:42
Thanks for all the screenshots. Very strange. 

Did you just disable Preview Pane? Does a hard refresh (hold down shift while clicking on the browser's refresh button) cure it? 

I see you have offline enabled but that shouldn't matter.

**Comment by Queuecumber** [comment] 2019-04-25 20:03
I've never had preview pane on and I tried shift-refresh and "empty cache and hard reload" but still the same behavior

Could it be something with the browser? I'm on chromium 75.0.3759.4

**Comment by leggett** [comment] 2019-04-25 20:15
It shouldn't be the browser... especially since it working on your other accounts. It must be something unique to that account.

Do you use other chrome extensions or advanced settings (under Gmail > Settings > Advanced)?

It is also possible Gmail changed some code and it is slowly rolling out and you're just one of the first to see it. If you're comfortable with the Javascript console and inspector, I can tell you how you can help me troubleshoot further.

**Comment by capellamtg** [comment] 2019-04-25 21:36
I also have this issue.

**Comment by Queuecumber** [comment] 2019-04-25 21:38
For better or for worse I am intimately familiar with the inspector, so let me know what kind of debugging you want me to do

**Comment by leggett** [comment] 2019-04-26 00:16
Awesome sauce. Can you right click and inspect the action bar. Ideally, div.G-atb like:

<img width="1440" alt="Screen Shot 2019-04-25 at 5 15 18 PM" src="https://user-images.githubusercontent.com/8763662/56775833-c7abaa80-677d-11e9-97bc-c968fa15180c.png">

**Comment by leggett** [comment] 2019-04-26 05:06
I think we found the problem -- it appears to break when you have Offline and Preview Pane enabled (I can repro this). From the screenshots, I see Offline enabled but not Preview Pane for @Queuecumber so this may not be a total fix.

**Comment by leggett** [comment] 2019-04-26 07:10
Ok, fixed in v1.2.6. Just pushed to the Chrome store. And I bumped the max-width for preview pane to 1680px. Let me know if you still have issues after the update.

**Comment by Queuecumber** [comment] 2019-04-26 12:26
Doesn't seem to be fixed for me, I never had preview pane on only online mode and I had already tried disabling it and done a hard reload and it hadnt fixed the problem then.

Heres the screenshot on the inspector of `div.G-atb`


![Screenshot from 2019-04-26 08-24-18](https://user-images.githubusercontent.com/5865387/56807476-f3ba4080-67fc-11e9-879f-f0483cf50694.png)

**Comment by Queuecumber** [comment] 2019-04-27 15:59
It's suddenly fixed today, maybe it was a caching issue

**Comment by Queuecumber** [comment] 2019-04-27 21:00
Actually I think I spoke too soon, it's doing it again, not sure what I did to trigger it or fix it before

**Comment by leggett** [comment] 2019-04-27 21:07
Bummer. Are you using offline and/or preview pane?

**Comment by Queuecumber** [comment] 2019-04-27 21:16
I was and I just turned them both off *but* I realized that I also had multiple inboxes turned on, which would be a difference from my other account that works fine. I toggled that off and it seems to have fixed it, and when I toggle it back on that breaks it again. I bet thats where the bug is

**Comment by leggett** [comment] 2019-04-28 16:30
Got it. I'll look into Multiple Inboxes. Thanks.

**Comment by jimbojnr81** [comment] 2019-04-29 00:39
If come across another issue. I seem to get a double overlay of the top right icons. It goes away when you view all in each inbox. It also changes the width of the emails to almost full width.
![image](https://user-images.githubusercontent.com/5010165/56872318-020d9400-6a6b-11e9-8f10-d4826a023574.png)

**Comment by leggett** [comment] 2019-04-29 01:42
Wait wait... are you using multiple inboxes AND preview pane?

**Comment by jimbojnr81** [comment] 2019-04-29 01:47
no, just multiple inboxes.

**Comment by leggett** [comment] 2019-04-29 02:21
You have the preview pane button in your action bar. It may be set to no split... but pretty sure it is enabled (Gmail Settings > Advanced > Preview Pane). No idea if that will fix it, but it is a combination I haven't tested.

**Comment by jimbojnr81** [comment] 2019-04-29 03:26
sorry i meant to say its not active now (it was when i took the screenshot) and it's still doubling up. 

strangely when i change the extra panels positioning to "right side of inbox" the double up goes away, but the layout of the inbox is terrible. 

![image](https://user-images.githubusercontent.com/5010165/56875154-42c4d780-6a82-11e9-8cf0-fa0ada856b5b.png)

**Comment by leggett** [comment] 2019-04-29 14:16
I can only reproduce this bug when both Preview Pane and Multiple Inboxes are enabled in Settings. Even if you switch Preview Pane to "No split" it breaks things. 

You can technically have both enabled but with Simplify disabled, when you enable both, Multiple Inboxes is ignored with Preview Pane enabled (again, even with it set to "No split"). So I will ignore multiple inboxes when preview pane is enabled and hide the additional action bars.

Pushing out in v1.2.9.

**Closed by leggett** 2019-04-29 14:16 UTC
Labels: bug
