### ISSUE TITLE
Simplify Icon Stands on Safari dark mode

### ISSUE THREAD

**Issue by MickEventide** [leggett/simplify#479] opened 2021-02-04 23:53 UTC
The Simplify icon stands out ike sore thumb in the Safari toolbar, especially in dark mode. Can the icon be updated to align with Safari's native styling?

**Comment by leggett** [comment] 2021-02-05 00:03
Hmm... I thought I was following the guidelines. But maybe not. Can you send me a screenshot of what it looks like for you (just the icon). I definitely don't want it to stick out like a sore thumb.

**Comment by MickEventide** [comment] 2021-02-05 02:45
Here's what I'm talking about. :)  Sore thumb is of course a subjective
term, but I hope you can see what I'm talking about. These screenshots are
from my M1 MacBook Air with Version 14.0.2 of Safari and Version 2.1.17 of
Simplify.

**Comment by MickEventide** [comment] 2021-02-05 02:46
Images fixed.

**Comment by leggett** [comment] 2021-02-05 03:15
I don't see the image sadly -- If easier, can you email it to hi@simpl.fyi?

**Comment by niccolomineo** [comment] 2021-02-05 11:17
Chiming it to add that the icon should comply with Apple's guidelines, I reckon starting from these resources: https://developer.apple.com/design/resources/

**Comment by nhojb** [comment] 2021-02-05 12:32
Here's the icon after enabling the extension:

<img width="559" alt="Screenshot 2021-02-05 at 12 31 11" src="https://user-images.githubusercontent.com/312540/107034133-2ead1e80-67ae-11eb-94b8-ae183505049a.png">

**Comment by nhojb** [comment] 2021-02-05 12:33
What's strange is that sometimes (after restarting Safari) it loses the blue background. But still has a feint black border. I can't reproduce right now, so no screenshot.

**Comment by niccolomineo** [comment] 2021-02-05 12:34
Shoudn't the icon be white?

**Comment by leggett** [comment] 2021-02-05 15:45
I forgot I updated the branding so recently. I'm on v2.1.25 on Chrome... so 8 updates. The new branding doesn't have the blue and follows Apple's guidelines. Will push v2.2 (the official v2 release) to all browsers today. Thanks for the report and stay tuned!

**Comment by leggett** [comment] 2021-02-06 19:28
Better (no blue) but still stands out in dark mode. I'll figure something out after launch.

<img width="233" alt="Screen Shot 2021-02-06 at 11 27 42 AM" src="https://user-images.githubusercontent.com/8763662/107127920-67acc800-686e-11eb-890d-14e6653c969f.png">

**Comment by leggett** [comment] 2021-02-06 19:30
(Looks great in not dark mode)

<img width="146" alt="Screen Shot 2021-02-06 at 11 29 47 AM" src="https://user-images.githubusercontent.com/8763662/107127950-a3e02880-686e-11eb-9794-af478f11153c.png">
<img width="171" alt="Screen Shot 2021-02-06 at 11 29 25 AM" src="https://user-images.githubusercontent.com/8763662/107127951-a478bf00-686e-11eb-884b-5fb53e1e62b1.png">

**Comment by niccolomineo** [comment] 2021-02-06 19:59
Hi Michael! I see you are trying to go more creative with this. Personally, I am fonder of a more minimalistic look, like Simplify's classic one - I have the impression it conveys the extension's aim of bringing "cleanliness". I would just use a non-narrow font variant, to make the overall look bolder. Something along the lines of the attached version (an inverted version could be useful for dark mode).
![Senza nome](https://user-images.githubusercontent.com/5409469/107128467-365be880-68be-11eb-8cfd-b49e9a2453a8.jpg)

**Comment by leggett** [comment] 2021-02-06 23:19
Thanks @niccolomineo -- this is a better version of the original and I like that it is monochromatic. But I struggled with this approach scaling up with the offering...

Something I've alluded to but not given a lot of details on, I will simplify more than Gmail. So I want a logo that works as a system across simplifying lots of apps. That also means multiple extensions (I don't want to do one extension that has access to a ton of sites) which means multiple extension icons (though I would expect you to hide most/all of them if you have many installed). I don't like that there is multiple icons but I think that con is worth the pro of tightly scoped permissions.

So here is how that looks for multiple properties:
![image](https://user-images.githubusercontent.com/8763662/107131780-6ab7b080-688e-11eb-805e-901ecbd1370b.png)

And a possible umbrella site (design wip):
![website](https://user-images.githubusercontent.com/8763662/107131800-9e92d600-688e-11eb-87de-535cff0aa5ee.png)

Thoughts?

**Comment by leggett** [comment] 2021-02-06 23:20
P.S. if you email me at hi@simpl.fyi, I'm happy to share my Figma file with the bajillion things I tried.

**Comment by niccolomineo** [comment] 2021-02-06 23:36
Hi Michael,
hope you are well. I would be glad to help you with the Simplify brand
image.

Niccolò Mineo
*niccolomineo.com* <http://niccolomineo.com/>


Il giorno dom 7 feb 2021 alle ore 00:20 Michael Leggett <
notifications@github.com> ha scritto:

**Comment by niccolomineo** [comment] 2021-02-06 23:37
I understand better now and I would be glad to help. You should have received an email from me.

**Comment by leggett** [comment] 2021-02-06 23:47
Looks like you replied to the GitHub ticket instead of to my email.

**Comment by leggett** [comment] 2021-03-29 14:44
Another complaint about this: https://twitter.com/taehtinen/status/1376444520322232320

**Comment by niccolomineo** [comment] 2022-03-23 06:56
@leggett, just a heads-up that you may want to close this.

**Comment by leggett** [comment] 2022-03-23 14:58
Close it as in finally fix it, right?

**Comment by niccolomineo** [comment] 2022-03-23 18:23
I thought you did change this already. My bad, I misunderstood.

**Comment by leggett** [comment] 2022-03-23 19:09
No worries! Safari has changed some so it isn't as ugly but I still intend to make it monochromatic and drop the background. It is embarrassing that I haven't already done that but other stuff just keeps getting prioritized.

**Comment by leggett** [comment] 2022-06-02 21:06
Apple finally approved my update for Safari and with it was a fix for the Simplify icon. I still encourage anyone using Simplify to customize their toolbar and hide the icon as I add the same menu inside Gmail.

**Closed by leggett** 2022-06-02 21:06 UTC
