### ISSUE TITLE
Email displays at full width of browser (no white space)

### ISSUE THREAD

**Issue by jupiter5000** [leggett/simplify#250] opened 2020-02-02 21:27 UTC
I think possibly since a recent update all my email displays at full monitor/browser width, making it very difficult to read emails and navigate/use.

Any advice? Using the chrome version.

Thanks

**Comment by filipporovelli** [comment] 2020-02-03 01:26
Same issue :(

**Comment by leggett** [comment] 2020-02-03 05:55
I'm not seeing it on my end yet... but that two of you are reporting this to suddenly be an issue, I fear something did change. I won't know what changed until I see it on my end. 

One thing that can cause this is if you have Preview Pane turned on under Gmail Settings > Advanced but change the setting to "No Split." If you don't use Preview Pane, it is best to disable it under Gmail Settings > Advanced. If you do use it sometimes and toggle the split, refresh Gmail after you toggle it to No Split as Simplify only detects the setup when Gmail loads.

**Comment by filipporovelli** [comment] 2020-02-03 06:39
It works for me! thanks @leggett 

Side note...I got 3 gmail accounts. Two of them are business. The issue happened just on the personal one.

**Comment by macx** [comment] 2020-02-03 09:31
That did the trick for me, as well, @leggett.

**Comment by jupiter5000** [comment] 2020-02-03 10:08
Worked for me also - many thanks @leggett. I appreciate all your hard work on this extension - it's a vast improvement over the standard interface (although I'm still mourning the loss of Inbox!)

**Comment by charliemiller** [comment] 2020-02-04 01:33
Experienced the same issue, and as with @filipporovelli only occurring with my non-GA account. Disabling Preview Pane and refreshing did the trick. Thanks @leggett, this extension truly rules. :)

**Comment by ldanielswakman** [comment] 2020-02-04 15:32
I also ran into this issue; turning off the Preview Pane option under Advanced Settings did the trick!

And amazing work on this extension; it's keeping my email inbox actually usable...

**Comment by mmoitas** [comment] 2020-02-04 21:16
Just to add a little more info to this issue:
- I have 2 Gmail accounts (personal and business)
- Both had the preview pane enabled
- The business account had the bug and was getting full width, I disabled the preview pane and now it is perfect
- Personal account was perfect but got the full-width issue when I DISABLED the preview pane, so to keep it centralized I have to keep the preview pane enabled on this account

I hope this helps. 
I can't live without this extension. Gmail is not a cognitive overload mess any more thanks to you 🙂 . Thanks!

**Comment by leggett** [comment] 2020-02-04 22:15
Thanks for the added info @mmoitas – two quick thoughts:

- Make sure you refresh Gmail after you enable preview pane or disable it because you weren't using it (had it always set to "No Split"). 

- If, after a refresh, you are still having issues in your personal account where disabling preview pane causes the inbox to go full width, can you email me at hi.simplify@gmail.com to debug? (assuming you're up for helping me debug)

**Comment by maxwellyoungio** [comment] 2020-02-05 05:05
The Preview Pane was also the cause of the issue for me - thanks for the solution :)

**Comment by Ronkimhi** [comment] 2020-02-05 09:52
Same here, thanks!

**Comment by RandiLeigh15** [comment] 2020-02-05 13:36
Thanks @leggett ! I disabled the preview pain and now my email doesn't trigger my anxiety! Hooray for some white space!

**Comment by luamado** [comment] 2020-02-06 10:58
Thank you so much @leggett worked for me too! it was driving me insane. Thank you for all your work on this extension. I miss Inbox every day

**Comment by shoeyn** [comment] 2020-02-06 17:05
Have the same issue and turning preview pane off did the trick, I'm assuming https://www.androidpolice.com/2020/02/06/gmail-multiple-inboxes-independent-scrolling-unified-toolbar/ has something to do with the change

**Comment by leggett** [comment] 2020-02-06 17:35
@shoeyn I hadn't seen that (nor has it arrived in my Gmail)! Thanks for the tip, I'll look into it.

**Comment by leggett** [comment] 2020-02-06 18:20
**Notes for myself:** check for `document.querySelectorAll('div.apI, div.apK')` and if you see that, alert user that they may want to disable preview pane if they don't want their inbox to be full width.

**Comment by leggett** [comment] 2020-02-06 18:24
FYI: I can reproduce this on one of my accounts now. Thanks again for the reports.

**Comment by KozKiller** [comment] 2020-02-07 23:24
So glad we were able to track this down. Love this addon too much to have it removed. Thanks all!

**Comment by joemidi** [comment] 2020-02-11 08:52
I don't seem able to disable the preview pane.

Is there a way round this?

<img width="1100" alt="Screenshot 2020-02-11 at 08 51 18" src="https://user-images.githubusercontent.com/2073312/74222170-c404f800-4cab-11ea-8c79-942582a0632b.png">

**Comment by leggett** [comment] 2020-02-11 15:02
@joemidi whoa... I'm guessing it is a managed G Suite account (a non @gmail.com address) and that your G Suite Administrator has the ability to enable and lock the feature it as enabled. Or maybe you had it enabled and they disabled the ability to use the setting and that disabled the setting instead of forcing it to "Disable". Either way, you would need to talk to your admin.

That seemed to be the opposite case for this person:
https://www.reddit.com/r/GMail/comments/a9pfn5/preview_pane_grayed_out/

If you can't get that fixed, I have a sort of fix coming for people that have preview pane enabled and set to No Split. It isn't a total fix (screenshot below) but it might make it tolerable. You could also use one of the preview panes (I'd recommend vertical).

<img width="1440" alt="Screen Shot 2020-02-11 at 6 59 44 AM" src="https://user-images.githubusercontent.com/8763662/74248413-661ce400-4c9c-11ea-8f76-e1a39f191424.png">

**Comment by leggett** [comment] 2020-02-12 09:24
Ok, the fix is in v1.7.7 and is live on Firefox (in seconds) and will take a couple weeks to get through Google's crazy slow review process for the Chrome Web Store. I will leave the bug open until that happens.

**Comment by leggett** [comment] 2020-02-13 15:14
@joemidi I found the admin setting. Select "Advanced Labs Management" under
https://admin.google.com/AdminHome?hl=en#AppDetails:service=email&flyout=labs And toggle "Preview Pane" from Enabled to Allowed.

**Maybe you could get your admin to not force it to be on?** 

![Screen Shot 2020-02-13 at 6 52 24 AM](https://user-images.githubusercontent.com/8763662/74448816-7960b880-4e30-11ea-994c-c5938f44f607.png)

**Comment by joemidi** [comment] 2020-02-14 14:58
No can do I'm afraid.

_This was requested to be set globally by upper management, and won't be changed unless approved by the same people._

**Comment by leggett** [comment] 2020-02-14 18:31
Ok, I've created another ticket to come back around and see if I can do something for those that have no choice. You can follow on #253

**Closed by leggett** 2020-02-14 18:31 UTC
Labels: bug

**Comment by leggett** [comment] 2020-04-13 23:15
THIS IS NOW SUPPORTED. Now-ish. I just checked in a fix for this. Going to send it to Firefox (where I can update it in minutes if there is an issue) and live with it for a few days with Reading Pane enabled ad set to No Split to make sure it is solid before I send it to Chrome (and wait for 1-2 weeks to get it published).
