### ISSUE TITLE
Input tool selection covers the search tooltip

### ISSUE THREAD

**Issue by RexYuan** [leggett/simplify#141] opened 2019-05-05 16:43 UTC
I'm using macOS Mojave 10.14.4 and Chrome Version 73.0.3683.103 (Official Build) (64-bit). Just installed the chrome plugin from the extension store. The input selection is covering the search tooltip, as shown below:

![Screen Shot 2019-05-06 at 12 38 10 AM](https://user-images.githubusercontent.com/5001650/57197261-bfcae200-6f97-11e9-9544-d92443b5f51d.png)

I tried reinstalling the plugin and logging out and in gmail again but didn't fix the problem. Not sure if this is reproducible.

Edit: btw, the input selection is enabled by Settings > Show all language options > Enable input tools

**Comment by leggett** [comment] 2019-05-05 18:07
Yeah... the problem is actually the support button. It looks like some styles changed causing my override to stop applying. I'll get a fix in.

**Comment by jyozwiak** [comment] 2019-05-05 18:58
I think I'm encountering this issue too. The Search button overlaps the other buttons (e.g., the Settings button) and is unclickable. 

![Screen Shot 2019-05-05 at 2 44 10 PM](https://user-images.githubusercontent.com/4589137/57198817-7782d400-6f45-11e9-8874-68ac4269ce51.png)
![Screen Shot 2019-05-05 at 2 46 37 PM](https://user-images.githubusercontent.com/4589137/57198818-7782d400-6f45-11e9-88eb-8a7bd74cebdd.png)
![Screen Shot 2019-05-05 at 2 49 46 PM](https://user-images.githubusercontent.com/4589137/57198819-781b6a80-6f45-11e9-9780-076abfd9f485.png)
![Screen Shot 2019-05-05 at 2 50 01 PM](https://user-images.githubusercontent.com/4589137/57198820-781b6a80-6f45-11e9-814c-42fda31acf58.png)

I can't click on the Search button in the last screenshot either (even though it doesn't overlap with the Settings button).

macOS Mojave 10.14.4 and Chrome Version 74.0.3729.131.

**Comment by leggett** [comment] 2019-05-05 19:00
I've got a fix for this but it is tangled up in a BUNCH of other changes I've been working on this weekend. Trying to get to a stopping point so I can push a fix.

**Comment by leggett** [comment] 2019-05-05 20:20
Just pushed as v1.3.0. Will take up to an hour to go live in the Chrome store. When you have v1.3.0, can you re-open this issue if it isn't fixed?

**Closed by leggett** 2019-05-05 20:20 UTC
Labels: bug

**Comment by RexYuan** [comment] 2019-05-06 07:39
It's fixed! 🎆 Thank you!
