### ISSUE TITLE
FR: Add additional fonts to composer

### ISSUE THREAD

**Issue by timfee** [leggett/simplify#613] opened 2021-08-24 17:41 UTC
If you do a search using our mutual previous employer for "change gmail font" you'll see a good number of requests from people who want to essentially be able to choose any [Google] web font from the dropdown.

I don't know if it'd be trivial to wrap everything in a `<div style="font: .....">` or if you'd need to traverse the elements in the composer and attach it to each child element, but if it's simple enough it could be a nice value add for people on the fence about a paid Gmail extension.

I know I'd love to use Inter (okay, actually `-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif`) as a "stationery" :)

**Comment by leggett** [comment] 2021-08-24 18:05
Simplify lets you change the font to "System font" which sets the font to `-apple-system, system-ui, "Segoe UI", Helvetica, Roboto, Arial, sans-serif`

I worry about performance of using a webfont that isn't bundled with the extension. 

I plan to pick some other fonts to bundle at some point. I had a chat with [Marcin Wichary](https://twitter.com/mwichary) on some possible fonts to use and he had some good advice.

**Comment by leggett** [comment] 2021-08-24 18:07
P.S. These fonts are only for changing your interface -- I am NOT trying to let you change what font you send your emails in for several reasons which on re-reading your request is what I think you were asking for?

**Comment by timfeeley-okta** [comment] 2021-08-24 18:08
I meant in the case of styling _outgoing_ messages.

![Screen Shot 2021-08-24 at 11 07 57@2x](https://user-images.githubusercontent.com/86313278/130667729-9d594cc1-2951-4cd3-88ed-f0afe74d8436.png)

**Comment by timfeeley-okta** [comment] 2021-08-24 18:10
Yeah. :)

It may be contrary to the mission to "Simplify" to let people choose Lobster as a font ;) Was thinking of it specifically for using clean system defaults in outgoing messages.

**Comment by leggett** [comment] 2021-08-24 18:24
Yup, I got that after I sent my first message. I'm not going to attempt this, so closing this issue. 

More detailed thoughts (stream of thoughts really):

- You can't bundle and use fonts with your message.
- I'm not even sure you can include references to external web fonts. And if you could, I'm not sure they would always be loaded by various clients or what the hit on performance would be.
- So the fonts that are on all computers would be the only ones you'd want to add. Ok, what about the string of system fonts you listed? That has a cascade that should hit a local font on each platform, right? 
- Now the problem is correctly wrapping all text in the correct font declaration. The problem with that is contenteditable (what Gmail uses for compose) is a _total_ beast and all kinds of odd things can happen and the fact that Gmail itself is trying to manage it.
- Even Gmail doesn't do a great job managing this. Set the body font to "Georgia" and then copy/paste some text from someone else's email (which is probably in Arial) and notice that it stays in Arial when pasted.

**Closed as completed by leggett** 2021-08-24 18:24 UTC

**Comment by leggett** [comment] 2021-08-24 18:32
We can achieve that by getting everyone to use Simplify and setting the system font to be the default :D

**Comment by timfee** [comment] 2021-08-24 18:51
#SimplifyTheWorld :)
