### ISSUE TITLE
Losing focus when composing mail

### ISSUE THREAD

**Issue by ymyke** [leggett/simplify#681] opened 2022-04-28 08:27 UTC
Love the extension!

I often have the issue that when I compose a mail (I think it happens mostly or only(?) when replying to mails) that, while typing my content, the focus switches from the compose window to Gmail's main app, resulting in my typing not ending up as text but being interpreted as keystrokes, archiving the mail I'm replying to or muting the thread etc., depending on what I've been typing.

Then I have to try and undo whatever has happened and use the mouse to put the focus back to the compose window.

I have not found a pattern yet that would allow me to reproduce. It happens maybe(!) 1 out of 5 times I compose a mail/reply. It happens both with all compose window variants: full-screen, in-line with thread, and popup.

Does anybody else have similar issues? Any idea what is going on here and what I can do?

---
System: Mozilla/5.0 (Windows NT 10.0
Edge Version 100.0.1185.50 (Official build) (64-bit)

**Comment by leggett** [comment] 2022-04-28 13:38
Yikes! 

Can you share a system report (gets attached when you start an issue report from inside Gmail -- see simpl.fyi/support)? Or at least let me know what version of Simplify you have?

**Comment by ymyke** [comment] 2022-04-28 14:00
Sure!

Simplify v.2.5.15 - Configuration: aAX appMenuOpen boldHighlight ca1 cfI cfK cfO cfR cfU composeActions composeFab composeFormat defaultTheme fontList fontMsg hideLabelChips hideListCount hideMsgCount hideSelectRefresh hideSignatures hideTabIcons inMsg invertAddons invertCompose izBg3 lightTheme listWidthLg lowDensity minimizeChat msgWidthSm nPane newUI simplify simplifyMenuOpen supExtWarn - System: Mozilla/5.0 (Windows NT 10.0 Win64 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 - Window: 1280 x 770 (100pct zoom) - Language: en

Also, here's a list of my extensions: Vimium, uBlock Origin, Onetab, Hypothes.is, Save to Pocket, LastPass

**Comment by leggett** [comment] 2022-04-28 19:30
Strange... v2.5.16 is the current version. And your first report said you were on Edge but this one says you are on Chrome 95 (old version of Chrome). Do you use both browsers?

Edge is currently behind a version (on v2.5.15 still) because Microsoft takes 1-2 weeks to approve updates whereas all other browsers approve them within 24 hours (often within an hour). So that might be part of the problem...

**Comment by leggett** [comment] 2022-04-28 19:31
P.S. There was a strange edge case around focus in v2.5.15 that I fixed in v2.5.16. So it might be getting the latest version fixes this for you. You can use https://chrome.simpl.fyi on Edge which is often more up to date.

**Comment by ymyke** [comment] 2022-04-28 19:38
* I do have both Edge and Chrome installed, but Simplify is only installed in Edge...
* I'm pretty sure I've been experiencing the issue for several (many?) weeks already. But I'll check if it still occurs w/ v2.5.16 and report.

**Comment by ymyke** [comment] 2022-04-28 19:39
re the PS: How do I use this? Just add it "over" my currently installed Simplify extension? Or remove the one I have installed first? Will I lose my settings?

**Comment by leggett** [comment] 2022-04-28 20:39
If you are switching from the version in the Microsoft app store to the one in the Chrome Web Store, then yes, you disable (or remove) the existing extension and install the one from Chrome's store. 

And yes, you will lose your Simplify settings unfortunately... I'm working on revamping settings and letting you sync them across devices but I don't have that ready yet.

**Comment by leggett** [comment] 2022-04-28 20:41
One other option: See if turning off this feature fixes things for now and wait for Edge to approve the update. 

I believe the issue was related to suppressing the emailing an external person warning. If you disable this, I think your issue will go away. You can re-enable it once v2.5.16 hits Edge.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/8763662/165841978-77a7878a-b239-4e5f-869f-79f7559683be.png">

**Comment by leggett** [comment] 2022-04-28 20:41
Disable this feature = choose "Don't suppress"

**Comment by ymyke** [comment] 2022-04-28 20:49
Thanks, I'll try.

**Comment by ymyke** [comment] 2022-05-03 14:30
I had the issue again just now. In spite of the settings above.

_Maybe_ this is the problem?

1. Searching for an author.
2. Reviewing the result list.
3. Composing a mail to that author.
4. Composition takes long enough for Gmail to refresh the result list and display the new draft which has the same author.
5. This update causes the focus to change to the main canvas.

That was my situation just now at least. Not sure if causation or (random) correlation.

**Comment by ymyke** [comment] 2022-05-12 05:24
Any comments?

**Comment by leggett** [comment] 2022-05-12 07:37
Sorry -- I missed your previous post. First off, [Simplify for Edge](https://edge.simpl.fyi) finally got updated to v2.5.16. 

I'm not able to reproduce the issue even with that workflow. I'm interested to hear that "composition takes long enough for Gmail to refresh the result list" -- are you saying that it took a while for compose to come up or that the list just took a while to update? 

I wonder if there is some kind of conflict with Vimium. Do you see the issue often enough that you could try to see if it goes away when you disable that extension?

**Comment by ymyke** [comment] 2022-05-16 06:39
"composition takes long enough for Gmail to refresh the result list" → This is simply refering to me taking long enough (typing, thinking) that the results list behind the compose window gets a refresh and the new (draft) email shows up in first position.

I never tried to disable Vimium so far. However, all the keystrokes are deactivated on Gmail with the catchcall pattern. So Vimvium but shouldn't react on any of the keystrokes.

Unfortunately I can't reproduce the problem w my workflow either. I'll be on the lookout for other patterns.

**Comment by leggett** [comment] 2022-05-16 06:56
Ok, I'm going to close this for now but re-open if you see it again or have any new insights. 

I don't move focus around too much in the current version but I do in the v3 beta with bundles. I'm checking to make sure focus isn't in a compose, input, or textarea before I move focus there.

**Closed as completed by leggett** 2022-05-16 06:56 UTC

**Comment by ymyke** [comment] 2022-05-16 07:49
I explored some more and can reproduce it now with this workflow:

1. Open an email thread.
2. Expand one of the mails in the conversation.
3. Hit shift-R to create a response (as a modal, where the thread is still visible).
4. Type a couple of letters. Wait a second or two.
5. Gmail will collapse the email that was expaneded in step 2. → Focus lost in the compose window.

(I also have a quick screencast, but I'd rather share it as a dm if you're interested.)

Turns out that the culprit is the ublock origins extension. Deactivating it or whitelisting gmail will get rid of the problem.

Any idea how to make this work with ublock origins? Would love to keep it active in gmail as well. But maybe it's not really necessary because Simplify also blocks all trackers?

**Comment by leggett** [comment] 2022-05-16 08:17
Very confused by step 5. Not sure why Gmail would collapse the email. Also not sure how/why uBlock origins would have any impact on this... very strange. 

No idea if uBlock blocks more than Simplify. In general, I've found the email spy trackers aren't on the adTracker block lists.

You can email me a screencast if you want to hi@simpl.fyi.
