### ISSUE TITLE
Compatibility with other extensions

### ISSUE THREAD

**Issue by dragoncalledk** [leggett/simplify#83] opened 2019-04-25 18:27 UTC
Hi! Love this, but it has a few very minor layout issues with the Copper extension. Here's a screenshot so you can see what I am talking about: https://1drv.ms/u/s!ApSeon_rCZ7cpbAkt6LPostsoJUmiQ

Any way to fix that?

**Comment by ebeldner** [comment] 2019-04-25 18:52
@dragoncalledk, getting an error when I click on the link. 

I'm also having the same issue but with a Boomerang plugin:
<img width="411" alt="Screen Shot 2019-04-25 at 11 49 32 am" src="https://user-images.githubusercontent.com/1638276/56760728-a84a5880-6750-11e9-8949-4c019070d0c4.png">

**Comment by leggett** [comment] 2019-04-25 20:07
Sorry but compatibility with other extensions isn't something I can support. There are too many of them and some change often. 

If/when things settle down, I might take a look at some of the popular ones and see if I can find a pattern to how they integrate themselves but nothing soon.

I do support add-ons (installed through Gmail > Settings gear > Get add-ons).

**Comment by leggett** [comment] 2019-04-25 20:08
With Gmail now supporting scheduled sending and their reminders on emails that you sent but didn't get a reply on... do you still need Boomerang?

**Comment by leggett** [comment] 2019-04-26 00:58
I'm going to start listing the various extensions people use if I ever dig into this: 
https://chrome.google.com/webstore/detail/dittach/nckdidfgpjgjblkhloeecdmofhgphkmm?hl=en

**Comment by leggett** [comment] 2019-04-26 00:58
https://chrome.google.com/webstore/detail/crm-for-gmail/hpfmedbkgaakgagknibnonpkimkibkla?hl=en

**Comment by leggett** [comment] 2019-04-26 00:58
Boomerang: https://chrome.google.com/webstore/detail/boomerang-for-gmail/mdanidgdpmkimeiiojknlnekblgmpdll?hl=en

**Comment by leggett** [comment] 2019-04-26 14:14
Clearbit Connection: https://chrome.google.com/webstore/detail/clearbit-connect-supercha/pmnhcgfcafcnkbengdcanjablaabjplo

**Comment by leggett** [comment] 2019-04-26 17:11
GMass: https://chrome.google.com/webstore/detail/gmass-powerful-mail-merge/ehomdgjhgmbidokdgicgmdiedadncbgf

**Comment by leggett** [comment] 2019-04-27 22:27
Mailtrack: https://chrome.google.com/webstore/detail/email-tracking-for-gmail/ndnaehgpjlnokgebbaldlmgkapkpjkkb

**Comment by aleemstreak** [comment] 2019-04-28 23:21
We (Streak, a gmail extension) make the [InboxSDK](www.inboxsdk.com) and we'd be happy to help make all the Gmail extensions that use the SDK be compatible with Simplify. 

In fact we made the SDK so that all these gmail extensions don't stomp all over each other - it powers some of the more popular gmail extensions:
Dropbox: https://chrome.google.com/webstore/detail/dropbox-for-gmail/dpdmhfocilnekecfjgimjdeckachfbec?hl=en
Hubspot: https://chrome.google.com/webstore/detail/hubspot-sales/oiiaigjnkhngdbnoookogelabohpglmd?hl=en
Streak: https://chrome.google.com/webstore/detail/streak-crm-for-gmail/pnnfemgpilpdaojpnkjdgfgbnnjojfik?hl=en-US

**Comment by dragoncalledk** [comment] 2019-04-29 14:23
Meh, totally understand what you're saying and think you've outlined a reasonable approach. I actually love the new Gmail and DESPISED Inbox, so this is far from a major issue. If it's a plugin that just works reliably with vanilla Gmail, I think that's really reasonable. Thanks for your reply and your work!

**Comment by leggett** [comment] 2019-04-29 15:02
I still plan to work on this... it just isn't high on my list.

**Comment by leggett** [comment] 2019-04-29 15:03
In fact, I'm more inclined now that I understand there is a single system I can integrate with (InboxSDK) to not mess up multiple extensions.

**Comment by thob** [comment] 2019-05-01 09:15
This extensions, Collabspot for SugarCRM, is essential for me https://chrome.google.com/webstore/detail/collabspot-sugarcrm-7-and/abolmnkelhknafibhnhnlgbhpoecimkm

**Comment by anthonysexton** [comment] 2019-05-14 11:01
Here's another one that doesn't quite work properly: https://chrome.google.com/webstore/detail/mixmax-email-tracking-tem/ocpljaamllnldhepankaeljmeeeghnid?utm_source=chrome-ntp-icon

Am loving Simplify though!

**Comment by mfoucher** [comment] 2019-05-14 16:45
We have confirmed that Mixmax, Mailtrack and Boomerang are having this issue with the extension.

**Comment by leggett** [comment] 2019-05-15 19:08
I've started working on this. 

**Update:** I looked at Boomerang, MixMax, Mailtrack, Streak in depth. I also looked at Dropbox and HubSpot Sales but they don't break Simplify, so I focused on the first 4.

- I'm detecting the presence of these 4 extensions, setting state under html.simpl.otherExtensions and caching state under localStorage.simplify[u].otherExtensions
- I've got Boomerang's pause inbox button fully hiding when the nav is closed, visible when the nav is open
- I am hiding the app bar menu icons for Boomerang, MixMax, Mailtrack, and Streak - confirmed this prevents them from breaking search with Simplify on BUT, since I haven't added a way to get to those icons, I'm not comfortable releasing it in this state yet.

My plan is to do with these icons as I do with the Google App Switcher -- show them all when you hover over the profile pic. I might add a little left arrow on the profile pic to better hint at this functionality. The real beast is going to be around triggering showing/hiding the tray correctly as these icons are not uniformly inserted into the DOM. So this may still be a week or so from being fixed.

**Question to those here:** Should I go ahead and push this out so these extensions don't break Simplify (and instead, Simplify will break them sort of)? Or should I wait until I have my plan fully implemented?

**Comment by anthonysexton** [comment] 2019-05-15 23:03
I can only talk to MixMax as that's the only one I use from that list but there is still a way to search, even when things don't lay out correctly. Given that, I'd be happy to wait until your plan was fully implemented as it seems like the right thing to do, rather than sending a potential heap of support requests the other way!

**Comment by leggett** [comment] 2019-05-16 16:39
Yesware: https://chrome.google.com/webstore/detail/yesware-email-tracking/gkjnkapjmjfpipfcccnjbjcbgdnahpjp?hl=en

**Comment by leggett** [comment] 2019-05-21 18:40
Salesforce Gmail extension:
https://chrome.google.com/webstore/detail/salesforce/jjghhkepijgakdammjldcbnjehfkfmha?hl=en-US

**Comment by leggett** [comment] 2019-05-27 06:33
Ok, I have something working for the 4 initial extensions: Boomerang, MixMax, Mailtrack, Streak. 

**What I've done:**

- I have hidden the app-bar buttons in the same way I've hidden the Google App Switcher (hover over the profile photo to access them; hover off the area to hide them again). 
- I've done a little simplifying of the extensions themselves 

**I need testers**

I don't use any of these extensions so I don't know if Simplify breaks them in other ways. 

I've published the new version that supports extensions as an unlisted version of Simplify Gmail for anyone who is willing to help me test it at **https://test.simpl.fyi**. 

Please comment here or open new issues for any problems you find. This test version is running the code that is here on GitHub so you can see the source.

**Comment by leggett** [comment] 2019-05-28 06:11
I'm seeing issues with Preview Pane and Boomerang... not sure why yet, but the entire action bar drops in z-index (or something else) making it inaccessible. The other 3 extensions don't seem to have this problem.

**Comment by leggett** [comment] 2019-05-30 05:57
Since no one is replying, I'm assuming this isn't going to work. So I guess I'll just push out what I have to the main version (it can't be much worse than how Simplify interacts with 3rd party extensions so far).

**Comment by vinnytroia** [comment] 2019-07-17 03:32
Hi. I am having this issue with a few plugins - one specifically is SalesHandy and SalesMate (CRM). Basically any app that adds an icon where Simplify has the search bar. As a quick hack to fix this, can you change the CSS layout of the search field to automatically push itself over if something is detected?

**Comment by leggett** [comment] 2019-07-17 05:55
I have to manually support them, but yes I can do that. I've done it for a handful of them. Can you link to their listing in the Chrome Store and I'll see what I can do.

**Comment by vinnytroia** [comment] 2019-07-18 03:29
Thanks! 

https://chrome.google.com/webstore/detail/free-email-tracking-sched/acfmebaomboldplijdpfepofggkocgnl?hl=en

https://chrome.google.com/webstore/detail/salesmate-crm-for-gmail/ekeefjfdbaakgbfbagacmckiedkmakem?hl=en

**Comment by ebozonne** [comment] 2019-08-20 10:16
Hi, we have a problem also with contact+ sidebar extension too :

- Buttons disappear after opening extension sidebar
- extension link: https://chrome.google.com/webstore/detail/contacts%20-for-gmail/cnaibnehbbinoohhjafknihmlopdhhip

thanks if any solution can be found

**Comment by macx** [comment] 2020-02-03 09:37
I'm using Copper as as CRM a lot. I installed [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) to enable user styled modifications. And this is my CSS to use Copper and Simplify as well.

```css
:root {
  --copper-drawer-width: 360px;
  --addon-width: 300px;
}

.gb_Kc {
  position: fixed;
  top: 62px;
  right: 14px;
}

.pw-expanded .gb_Kc {
  right: calc(var(--copper-drawer-width) + 14px);
}

.addOnsOpen .gb_Kc {
  right: calc(var(--addon-width) + 14px);
}

html.simpl.hideSearch .pw-expanded .aeH {
  width: calc(100vw - 172px - var(--copper-drawer-width));
}

html.simpl .pw-expanded .z0 {
  left: calc(100vw - 92px - var(--copper-drawer-width));
}

html.simpl .pw-expanded .bAw {
  right: calc(47px + var(--copper-drawer-width)) !important;
}

html.simpl .AO .aeF > .nH {
  margin-top: 10px;
}

@media only screen and (min-width: 1291.98px) {
  .pw-expanded .G-atb {
    padding-left: calc(((100vw - var(--content-width)) / 2) - var(--left-offset) - var(--copper-drawer-width)) !important;
  }
}

```

Sometimes, GMail is changing the Markup class names, it's mainly `.gk_KC` what has to be changed to the new name, if a new version is published.

**Comment by patwalls** [comment] 2020-03-11 14:30
I have a customer who is reporting an incompatibility with the sidebar functionality of InboxSDK + Simplify. They can't hide/show the sidebar, the buttons are missing.

(you're probably already aware of this)

I confirmed Simplify causes this by installing on my own.

**Comment by leggett** [comment] 2020-03-11 20:29
@patwalls the buttons aren't missing and they still work (to show/hide the sidebar including 3rd party extensions using InboxSDK and those that don't). 

The are moved into the button above the compose button in the bottom right. Hover over that button and you can click on the add-ons to show/hide them. You can also typically click an X in the top right corner of the sidebar to close the sidebar.

![add-on-menu](https://user-images.githubusercontent.com/8763662/76461004-4b718400-639c-11ea-9dc9-339737d8442b.gif)

**Comment by patwalls** [comment] 2020-03-11 20:52
@leggett Thank you!! This is awesome.

**Comment by moikirsch** [comment] 2020-09-17 22:05
> Please comment here or open new issues for any problems you find. This test version is running the code that is here on GitHub so you can see the source.

I do use Mailtrack so I can go ahead and test that version.

**Comment by CarlosRebolledo** [comment] 2020-10-01 00:28
Hola Michael !!! 

Una extensión interesante y que voy a probar con Simplify es DRAG https://chrome.google.com/webstore/detail/drag-organize-and-share-y/kadokpknocdadnipihnphaaabanedjnb y https://www.dragapp.com/

**Comment by CarlosRebolledo** [comment] 2020-10-01 00:29
Otra extensión interesante es Gmelius https://chrome.google.com/webstore/detail/gmelius-for-gmail/dheionainndbbpoacpnopgmnihkcmnkl

**Comment by leggett** [comment] 2021-02-06 00:56
Here is the state of things with Simplify v2:

**Works as is (yay)**

- Clearbit Connect
- Contacts+ for Gmail
- Dropbox
- Inbox When Ready
- Gmail Tabs (by CloudHQ)
- Todoist

**Did something so it works**

- Boomerang
- Calendly
- FlowCrypt
- Gmass
- Gmelius
- Inboxy
- Mailtrack
- MixMax
- Pause Gmail (by CloudHQ)
- Streak

**Not compatible** (I don't block them, but I pop up a warning every time you load Gmail that says you should disable SImplify or the other extension)

- Cooper CRM
- Drag
- Hubspot
- Salesforce
- Sales Handy
- Sortd
- Yesware

**Comment by leggett** [comment] 2021-02-13 06:56
Ok, basic support for Copper is included with the next update (v2.2.3). I'm pushing to testers now and hope to push on the public release by Monday.

**Comment by leggett** [comment] 2021-02-21 01:42
Basic support for Hubspot will go out late next week in v2.3.1.

**Comment by scotteaton** [comment] 2021-02-27 23:38
Is ActiveInbox on your list? I did not see it. I have been a user of this extension from the beginning and would prefer not to lose it as part of adopting your extension.

**Comment by leggett** [comment] 2021-02-28 00:17
I wasn't aware of that extension. I'll look into it but from the screenshots in the Chrome Store, I suspect it will be too hard to make compatible. Have you tried using them together?

**Comment by scotteaton** [comment] 2021-02-28 01:18
Yes. They don't play nice together.

**Comment by leggett** [comment] 2021-02-28 18:49
Not sure when all of this will go out as I'm focused on building the subscriptions now.

I've made some minimal adjustments to play a little nicer with ActiveInbox but as I don't use ActiveInbox, I'm not sure if my changes are enough. As such, I will throw a warning that the two extensions are likely not compatible. For these cases where they aren't great together but kind of work, I might add some way to "use at your own risk" where you can opt to not see the warning every time you load Gmail. 

Also their extension appears to be a bit buggy even with Simplify disabled. 

- It doesn't support Gmail's new nav (their "New task" button overlaps the compose button) and their notes 
- Their subtasks and notes fields overlap the conversation as you scroll

**Comment by scotteaton** [comment] 2021-02-28 23:45
Understood. Thank you.

**Comment by leggett** [comment] 2021-03-07 16:10
I'm closing this issue and starting a new one so I can have the list of extensions that are supported / not supported at the top.

**Moved to: https://github.com/leggett/simplify/issues/554**

**Closed by leggett** 2021-03-07 16:10 UTC
Labels: enhancement
