### ISSUE TITLE
Minimized search bar prevents opening of filters until user writes something

### ISSUE THREAD

**Issue by wtfzambo** [leggett/simplify#259] opened 2020-03-11 15:11 UTC
Hello,
I'm not sure if it's intended behavior or not, but since this doesn't happen with non-minimized search bar, I believe it may be a bug.

As title says, if one clicks on the down arrow to open filters, using minimized search bar, it just closes again, unless something is written in the bar itself. I attached a gif that better illustrates what I'm talking about.

![simplify](https://user-images.githubusercontent.com/47462792/76432144-d9586980-63b2-11ea-9cae-5b0134b148ee.gif)

**Comment by markbknight** [comment] 2020-03-28 23:46
This happens to me too. It's tough trying to write in the tiny space up there. 
Image attached

![FireShot Capture 674 - Inbox (133) - markbknight@gmail com - Gm_ - https___mail google com_mail_u_0_](https://user-images.githubusercontent.com/39030637/77836462-a7723180-712c-11ea-8da3-f31a393779a5.png)

**Comment by leggett** [comment] 2020-04-02 18:08
@wtfzambo Nice catch -- I should make sure the create filter pane isn't open when I collapse the search box. Will fix.

**Comment by leggett** [comment] 2020-04-02 18:08
@markbknight The search bar should NOT be that narrow when you are searching -- it is supposed to expand quite a bit when you focus it. I'll look into this too.

**Comment by leggett** [comment] 2020-04-04 14:40
Having the Reading Pane enabled but set to No Split is definitely pretty broken right now. That's the thing I'm trying to fix first.

**Comment by leggett** [comment] 2020-04-30 18:35
@wtfzambo I've got a fix for the search box (and the advanced search form with it) closing when you click on the down arrow. It will go in the next version.

**Comment by leggett** [comment] 2020-04-30 18:52
@markbknight I'm not able to reproduce your issue. It is definitely separate from the original issue so if you are still having issues, can you open a new ticket so we can track it down?

**What I'm seeing**
It appears that you are in your inbox with the actions visible but no message selected. Typically the only way you can do that is if you have Reading Pane enabled but it doesn't look like that is the case. Or is it?

**Related issues**
It looks like you have either Multiple Inboxes or Unread First enabled for your inbox, text button labels (instead of icons), and a very narrow window. 

There is a bug where I'm not detecting Multiple Inboxes since Gmail changed how it is coded. I'm about to fix that. With text labels, I see the search box overlapping the buttons at some resolutions... I'll put in a blunt fix for that (I'm just going to shrink the width of the action bar when the search box is focused). 

**In v2**
I'm about to start working on Simplify v2 and I have new plans for how the search box is handled (much closer to how it was in Google Inbox) which should make all this a lot better in any setup.

**Closed by leggett** 2020-04-30 18:52 UTC
Labels: bug
