### ISSUE TITLE
Scrolling part way down messages

### ISSUE THREAD

**Issue by wesort** [leggett/simplify#166] opened 2019-05-15 17:06 UTC
NB: I don't _know_ if this relates to Simplify.

**The issue:** Some messages / threads are scrolling partway down the message when they are opened. These are from different senders and I don't spot a pattern.

**Tests:** I've disabled Simplify but the buggy behaviour persisted. Removing Simplify resolved the issue for me. 

**Context:** 
- Chromebook Pixel LS (2015)
- Version 75.0.3770.24 (Official Build) beta (64-bit)
- G Suite Business

**Comment by leggett** [comment] 2019-05-15 17:32
While this sounds like it couldn't be caused by Simplify... I've given up on saying, "no way that is caused by Simplify" because sometimes it is. 

I haven't seen it myself (and I use it on G Suite, a personal account, and a delegated account). If you want to try and troubleshoot, I'd pay attention to how long the emails are that you are opening (really long, less than a page, etc?) and the read state (is it multiple messages, some unread or all unread... or just one message?). It might be somehow caused by my adding padding to the end of the conversation but that doesn't really make sense.

Other useful context:

- other chrome extensions you use that modify Gmail 
- any advanced Gmail features you have enabled (preview pane, custom keyboard shortcuts, etc)

**Comment by leggett** [comment] 2019-05-16 21:16
I'm going to close this for now since I can't reproduce the issue. If you see it again or have more information, please re-open or just comment.

**Closed by leggett** 2019-05-16 21:16 UTC

**Comment by wesort** [comment] 2019-05-16 21:20
Thanks Michael - I definitely appreciate it's pretty unlikely that Simplify is to blame here. However, I did debug this for about half an hour before reporting including turning off other extensions and disabling Gmail labs.

All that said, I've just now reinstalled (again) and I can't recreate the issue either. 🤷‍♂  So I'll leave this closed unless I experience it again and if that happens I will try and caption more info.
