### ISSUE TITLE
Support Gmail's new design

### ISSUE THREAD

**Issue by Julian88Tex** [leggett/simplify#605] opened 2021-08-08 19:25 UTC
I'm noticing a number of issues that began around 8/6/2021. I'm not positive but it looks like Gmail had a bit of a design change that I suspect caused these new issues. I'm noticing it in a Gsuite Gmail account only since it's the only one with the [redesign](https://9to5google.com/2021/06/14/gmail-google-chat-spaces/).

<img width="89" alt="Screen Shot 2021-08-08 at 12 16 17 PM" src="https://user-images.githubusercontent.com/459099/128643261-d01b5637-0124-4271-886b-5ab8329f1799.png">

There appears to be a variety of issues but the most obvious ones are buttons disappearing or overlapping each other and/or the search bar intermittently. Also, the Gmail dark mode and Dark Reader are not changing most (Gmail) or any (G Suite) visuals to dark.

<img width="1463" alt="Screen Shot 2021-08-08 at 12 12 53 PM" src="https://user-images.githubusercontent.com/459099/128643397-06e18f0b-89f9-45ad-8235-a462e885a103.png">
<img width="1032" alt="Screen Shot 2021-08-08 at 12 10 59 PM" src="https://user-images.githubusercontent.com/459099/128643398-d1c08b1e-886c-44bc-b7a8-a90314569747.png">
<img width="1115" alt="Screen Shot 2021-08-08 at 12 10 55 PM" src="https://user-images.githubusercontent.com/459099/128643400-cc877d11-b131-40da-8796-1d5a2c789170.png">

Workaround:
Hide Meet section in Gmail
Settings Gear -> See All Settings -> Meet (G Suite) / Chat and Meet (Gmail) -> "Hide the Meet section in the main menu" -> Save
<img width="629" alt="Screen Shot 2021-08-08 at 12 18 45 PM" src="https://user-images.githubusercontent.com/459099/128643473-d6bdead2-11f7-4ff2-b0f1-7ba41f63de8c.png">

Note: 
What I turn off Simplify dark mode and other issues do not occur even with Meet section enabled.

**Comment by leggett** [comment] 2021-08-08 21:20
Thanks for the report! This does look like some changes to Gmail. I'll look through my test accounts to see if I've got the update anywhere so I can work out what I need to do to support the changes.

**Comment by leggett** [comment] 2021-08-09 01:17
I looked into this and unfortunately, I don't have it on any of my test accounts. It looks like the [redesign](https://9to5google.com/2021/06/14/gmail-google-chat-spaces/) Google previewed in June. 

I suspect the change is sizable and will require a big update to Simplify. But I can't really do that without access to an account myself unfortunately. As soon as I get it, I will work to get the update out ASAP.

**Comment by leggett** [comment] 2021-08-09 02:50
One thing that might help me prepare some is if you could email hi@simpl.fyi full screenshots. It can be of your spam folder and it would help if you could show me the following:

- Vertical reading pane, nav open
- Vertical reading pane, nav minimized
- No reading pane, nav open
- No reading pane, nav closed

No worries if you're not comfortable sending these or don't have time to. Thanks again for the original report and screenshots.

**Comment by Julian88Tex** [comment] 2021-08-10 02:24
@leggett My pleasure and no problem just sent those over. I think I covered all of them but let me know if I misunderstood.

**Comment by Julian88Tex** [comment] 2021-08-10 02:25
@leggett Checked a few of my other gmail accounts and it appears to be in my G Suite account only. I thought it was occurring in non-redesigned account too but I think that may have just been a cache issue temporarily. I'll update the Issue to specify.

**Comment by johnpeele** [comment] 2021-08-20 16:06
@leggett Also, not sure if you're technically supporting Brave, but all my Google Workspace accounts have UI issues in Brave. My personal Gmail account works as intended.

**Comment by leggett** [comment] 2021-08-21 22:44
@johnpeele I support Brave. If it looks anything like the screenshots at the top of this issue, I suspect it is not your browser but instead that you too have the new UI from Google (which I have yet to get in any of my Workspace test accounts). I am eagerly waiting to get the update so I can support it.

Let me know if your issue is different.

**Comment by leggett** [comment] 2022-01-08 18:22
@Julian88Tex -- do you still have this UI or did it go away? It seems that Gmail never launched it (or they scaled it way back).

**Comment by Julian88Tex** [comment] 2022-01-09 05:38
@leggett I actually have been using Superhuman for months now so I've had Simplify turned off. Just turned it back on and as best I can tell things are looking pretty good. I'm having a hard time remembering old vs. new design. But here's what I see:

<img width="1920" alt="Screen Shot 2022-01-08 at 9 37 20 PM" src="https://user-images.githubusercontent.com/459099/148670730-452e859c-38b4-459d-be04-606c0ea4470a.png">

Only potential issue I'm noticing is search isn't dark after clicking on it:

<img width="642" alt="Screen Shot 2022-01-08 at 9 38 42 PM" src="https://user-images.githubusercontent.com/459099/148670747-13cfb1bb-1172-4347-9092-0424054e69b4.png">

**Comment by leggett** [comment] 2022-01-09 05:53
Looks like the changes rolled back. I'm going to close this bug. 

And yes, menus and auto-complete aren't inverted (yet). I've got a long list of things I want to do to dark mode. Going to finish bundles first.

**Comment by leggett** [comment] 2022-02-02 20:11
This is [finally happening](https://workspaceupdates.googleblog.com/2022/01/new-integrated-view-for-gmail.html). We'll see what the damage is when it launches next week.

**Comment by ImSorryButWho** [comment] 2022-02-25 12:49
This just rolled out to one of my accounts.  One minor issue that immediately pops up: the compose button is a bit cut off on the right side, and tries to spell out "Compose" but only has "Co".

![image](https://user-images.githubusercontent.com/91785526/155717873-a59bc463-4ed2-4bb7-a355-847417728c87.png)

**Comment by leggett** [comment] 2022-02-25 15:21
@ImSorryButWho Thanks -- I haven't gotten access yet but hope to any day now so I can address all issues.

**Comment by macx** [comment] 2022-03-02 07:04
It rolled out for my private GMail but not for me Workspaces. With Meet and Chat turned off, all looks fine. With Meet and Chat turned on the new design have some issues regarding the sidebar pane und buttons.

**Comment by leggett** [comment] 2022-03-09 09:18
Just pushed v2.5.14 to support Gmail's new design. Should reach everyone within ~24 hours.

Video tour here: https://www.youtube.com/watch?v=zLmrhLEuRzY

**Closed as completed by leggett** 2022-03-09 09:18 UTC

**Comment by erikgeurts** [comment] 2022-03-09 09:30
As a mater of fact, it arrived already in my setup 10 minutes after you pushed it!
