### ISSUE TITLE
Notification for low space or vacation auto-responder breaks layout, links not clickable

### ISSUE THREAD

**Issue by KitClement** [leggett/simplify#51] opened 2019-04-11 08:06 UTC
![image](https://user-images.githubusercontent.com/6166412/55940938-024a0a80-5bf6-11e9-8b8b-b3ed418384c0.png)

Image above shows bug.

**Comment by leggett** [comment] 2019-04-11 15:30
This is going to be hard to reproduce and address. You can press Command+J (on mac) or Win+J (on Windows) to temporarily disable Simplify so you can click on the links.

**Comment by sweinreich** [comment] 2019-04-11 16:49
A similar banner and visual bug appear when setting up email forwarding (the banner appears for 7 days for security reasons). I just hid the banner (class `ZY`), but this wouldn't be a good general solution.

**Comment by sweinreich** [comment] 2019-04-11 16:50
A similar banner and visual bug appear when setting up email forwarding (the banner appears for 7 days for security reasons). I just hid the banner (class `ZY`), but this wouldn't be a good general solution.

**Comment by leggett** [comment] 2019-04-30 07:08
v1.2.9 fixes the vacation auto-responder. Can someone with account delegation or the low-space notification tell me if it fixed those too?

**Comment by leggett** [comment] 2019-05-08 06:42
I've now fixed the account delegation too. Can't test the low space error... if you have that, let me know and I'll tell you how you can help me fix it too.

**Comment by cy2k** [comment] 2019-05-13 20:05
> I've now fixed the account delegation too. Can't test the low space error... if you have that, let me know and I'll tell you how you can help me fix it too.

Sorry I'm just seeing this issue now, and I see you've closed it already. If it can be reopened, I'd be happy to help troubleshoot this issue since I'm having it now. :)

![Screen Shot 2019-05-13 at 4 02 08 PM](https://user-images.githubusercontent.com/3419396/57650446-d32e0c80-7598-11e9-88a5-cc05671cfdc6.png)

**Comment by leggett** [comment] 2019-05-13 20:48
Great!

Go to your spam folder or something. Then, right click on the yellow low-storage banner and select "Inspect element." That should open up the javascript console. Then just send me a screenshot of your whole window.

**Comment by leggett** [comment] 2019-05-13 20:50
Also, I can make this dismiss-able if you want. It would come back every time you reload the page. I kind of think it shouldn't go away as this is a pretty bad state to have your account in. But the place I move these warnings (bottom left corner like notification) might be pretty annoying if it never goes away. Thoughts?

**Comment by cy2k** [comment] 2019-05-14 04:19
OK, here's the screenshot, let me know if that works for you.  I'm assuming this was to capture the div or something like that?

![2019-05-14 00_14_19-Gmail](https://user-images.githubusercontent.com/3419396/57670501-946e7580-75dd-11e9-86f4-8b76b81578ca.png)

As far as what to do with it... I think, at least for this one, since it's a storage issue that you would (in theory) want to deal with quick-ish, I think having it never go away until you deal with it is a fine approach.  I haven't personally seen the warnings you're mentioning, though, can you share a screenshot of what that would look like?

**Comment by leggett** [comment] 2019-05-14 04:21
Thanks for sending the screenshot. Unfortunately, that is the action bar, not the notification banner. Try right clicking on it above the search box maybe. If you get the right one, it should highlight the yellow bar in blue the way the action bar is highlighted in blue in that screenshot.

**Comment by leggett** [comment] 2019-05-14 04:22
And yes, I'm trying to see what the classname is on the div for the notification banner so I can change how it is displayed.

**Comment by cy2k** [comment] 2019-05-14 18:04
Ah good call, the divs must be overlapping so I picked the wrong one.  This looks right.

![2019-05-14 14_01_14-Gmail banner 2](https://user-images.githubusercontent.com/3419396/57721051-34b1b200-7651-11e9-9e0a-8e5023b5c03d.png)

**Comment by leggett** [comment] 2019-05-14 22:36
Perfect. Thanks for the screenshot -- couldn't have done it without that. 

I'll include a change for this banner in the next update that restyles it as a black box and moves it to the bottom left corner. Would you please report back if it doesn't work or looks odd in any way?

**Closed by leggett** 2019-05-14 22:36 UTC
Labels: bug
