### ISSUE TITLE
Select all checkbox no longer inline with the ones below

### ISSUE THREAD

**Issue by group7access** [leggett/simplify#388] opened 2020-09-12 02:44 UTC
My brain keeps wanting to put a check in the "select all" checkbox directly above the checkboxes below - however, now it is off-center to the left.

![image](https://user-images.githubusercontent.com/70614907/92985437-bac15100-f46f-11ea-9951-8fe9c9ff46d8.png)

Windows 10
Chrome
1920 x 1080 resolution

**Comment by leggett** [comment] 2020-09-12 14:59
Definitely a bug -- they are supposed to line up. Will fix.

**Comment by group7access** [comment] 2020-09-12 23:31
@leggett - Looking good now!

**Comment by group7access** [comment] 2020-09-13 20:05
Off center again today:
![image](https://user-images.githubusercontent.com/70614907/93027454-24557280-f5ca-11ea-993b-c34597c7d4b1.png)

**Comment by leggett** [comment] 2020-09-13 20:15
I haven't fixed it yet... sometimes refreshing Gmail fixes it for a while which is probably what you saw.

**Comment by group7access** [comment] 2020-09-13 20:17
I thought perhaps that what was going on. This time I will actually wait to hear back from you before I test it again ;)

**Comment by leggett** [comment] 2020-09-14 23:25
I thought I knew what this was but I'm not able to reproduce it. There was a similar problem in conversation view (that I just fixed) but not in list view. Do you have other extensions running that modify Gmail?

If not, could you email me a screenshot of your whole window? You can use your spam folder so nothing private is shared and you can email it to me at hi@simpl.fyi instead of posting here.

**Comment by group7access** [comment] 2020-09-14 23:33
I believe the only extension that can modify Gmail is the Bitmoji one (adds an icon to the right of the Send button in the New Message window). Here are all of my extensions:

![image](https://user-images.githubusercontent.com/70614907/93148136-56d99b00-f6b0-11ea-97ad-ecf8d29c2b63.png)

**Comment by group7access** [comment] 2020-09-14 23:33
I have disabled the Bitmoji one and will monitor the select all checkbox's location.

**Comment by leggett** [comment] 2020-09-14 23:38
Thanks for trying. Bitmoji has caused other issues... I haven't added it to explore what all it is doing but that could be the problem.

**Comment by group7access** [comment] 2020-09-14 23:42
(Sent from my phone 😉).

Will let you know!

**Comment by leggett** [comment] 2020-09-15 06:39
Do you use horizontal reading pane (where the inbox is above the message)?

**Comment by group7access** [comment] 2020-09-15 11:06
I do not use this.

**Comment by leggett** [comment] 2020-09-16 05:03
I'm going to close this out... looks like it is Bitmoji: https://github.com/leggett/simplify/issues/373

**Comment by group7access** [comment] 2020-09-17 01:39
My Bitmoji extension has been disabled since Sep 14, yet this continues to happen - just happened again now:
![image](https://user-images.githubusercontent.com/70614907/93409380-0602a780-f854-11ea-9cc2-5dd443c22ccf.png)

I have now completely removed the Bitmoji extension from my Chrome and will disable ALL other extensions in the spirit of helping to find what is causing this.

![image](https://user-images.githubusercontent.com/70614907/93409520-51b55100-f854-11ea-8f9a-0753a5bc816b.png)

**Comment by leggett** [comment] 2020-09-17 02:03
Thanks for the update. Just to confirm, you have Simplify v2.1.10, yes? Some have reported the beta isn't auto updating. You can see at the bottom of Simplify Settings.

**Comment by group7access** [comment] 2020-09-17 02:07
Confirmed:
[image: image.png]

**Comment by group7access** [comment] 2020-09-29 01:57
This is still happening for me on 2.1.11 - However, I will stop sending you these as it's not the end of the world ;)

![simplify](https://user-images.githubusercontent.com/70614907/94503937-e14bef80-01c4-11eb-9bbf-65fa85c5abe4.gif)

**Comment by leggett** [comment] 2020-09-29 14:57
Ooohhh... it is because the nav is being incorrectly detected as closed when it is open. Thanks for the update. I have a separate bug tracking this I think. I'll make sure before I close this as a duplicate.

**Comment by leggett** [comment] 2020-09-29 22:40
Confirmed -- this is a duplicate for #395

**Comment by group7access** [comment] 2020-09-29 22:46
But I submitted mine first 😉
https://github.com/leggett/simplify/issues/388#issuecomment-691719519

Glad to hear it's still on your radar!

**Comment by leggett** [comment] 2020-09-30 16:55
To confirm: this only happens when you first load Gmail and not randomly while you're using it, correct?

Do you quit your browser and/or shut down your computer often? I'm wondering if this somehow happens most often when you boot up your computer or open your browser for the first time.

**Comment by group7access** [comment] 2020-09-30 18:09
It is happening randomly as I move between messages and back to my inbox. I
do close my browser once or twice a day, and restart my machine every 2-3
days.

**Comment by leggett** [comment] 2020-09-30 18:49
Hmm... well maybe I was wrong to merge the two issues then. :/

The only time I try to detect the state of the nav is when Gmail first loads. Opening and closing messages or jumping around Gmail shouldn't try and detect the nav state. I've made some changes to how I detect that on load to account for some possible edge cases... but your issue is while using Gmail.

So now I'm thinking there is some way to open/close the nav that I'm not observing such that the nav is opened or closed and Simplify isn't aware causing Gmail and Simplify to get out of sync. I'll see what I can do.

**Comment by leggett** [comment] 2020-09-30 19:39
Ok, made some changes. Going to ship what I've got in v2.1.12 and we'll see if it fixed it or not.

**Closed** 2020-10-13 17:09 UTC
