### ISSUE TITLE
Group by date seems to break after deleting a message

### ISSUE THREAD

**Issue by nhojb** [leggett/simplify#319] opened 2020-08-31 17:26 UTC
1. Select a message
2. Delete it
3. Date groups disappear

Note: the rules around when this bug is triggered appear to be complex. For some reason everything works ok my "Primary" and "Updates" tabs, but not in the other tabs.

Also see attached screen capture.

[Simplify Date Groups.m4v.zip](https://github.com/leggett/simplify/files/5151675/Simplify.Date.Groups.m4v.zip)

**Comment by BickitySnow** [comment] 2020-08-31 19:51
On a UX note for the Group by Date, personally I prefer the v1 color division. 

<img width="1241" alt="Screen Shot 2020-08-31 at 3 48 26 PM" src="https://user-images.githubusercontent.com/59098468/91760732-e0ae4200-eba1-11ea-99c8-ca7032356981.png">

**Comment by leggett** [comment] 2020-08-31 22:11
@nhojb Interesting! Oddly, I can't reproduce the issue myself. Were you in your inbox?

@BickitySnow It definitely makes it easier to see where the gap is but it also makes the inbox more noisy when there isn't much in it and makes the labels harder to read in some themes. I don't think I'll return to how v1 did it but will stew on it some more.

**Comment by nhojb** [comment] 2020-09-01 13:16
I can reliably reproduce the issue in the "Social" and "Promotions" tabs, but not in "Inbox" or "Updates". Sometimes even selecting a message (via mouse) can trigger the bug.

**Comment by leggett** [comment] 2020-09-01 14:02
Boom! Got it now. Will hunt it down.

**Comment by danielanewman** [comment] 2020-09-01 16:14
+1 on selecting a message by mouse triggering this bug!
![2020-09-01_12-11-37 (2)](https://user-images.githubusercontent.com/5234389/91877919-9df57400-ec4c-11ea-948e-a924c24feeea.gif)

**Comment by leggett** [comment] 2020-09-14 21:53
Got a fix for this in the next update.

**Closed by leggett** 2020-09-14 21:53 UTC
Labels: v2

**Comment by leggett** [comment] 2020-09-14 21:54
@danielanewman I'm not sure what's going on in your screen grab... I'm hoping it fixes that for you too but let me know if you still see it.
