### ISSUE TITLE
Entered templates disappear

### ISSUE THREAD

**Issue by CarlosRebolledo** [leggett/simplify#451] opened 2021-01-03 14:26 UTC
It has happened to me twice. I enter templates and work with them during the day but then they disappear. My templates are zero.

Although today there is a template used a couple of days ago, the others are not.

I do not know why, but I raise it to see if it is happening to someone else and see if Michael can give it a look

A hug and happy 2021 to everyone

**Comment by leggett** [comment] 2021-01-03 16:32
Assuming you're on the latest beta version, can you press Alt+I (Opt+I on Mac) and send me the setup info shown in the dialog?

**Comment by CarlosRebolledo** [comment] 2021-01-03 16:34
Ok, se inserta 

Simplify v.2.1.16

Configuration:
simplify lowDensity ca2 caD cfC cfF cfI cfO cfS cfU composeActions composeFormat dateGroup debug hideSignatures bgOff invertAddons minimizeChat showChat js-focus-visible aAX lightTheme defaultTheme navOpen inInbox inList nPane

**Comment by leggett** [comment] 2021-01-03 16:41
Thanks. One more question: how many templates do you have?

**Comment by CarlosRebolledo** [comment] 2021-01-03 16:48
At this time only one that has existed for 3 days without being deleted.

Before that, the 5 that I usually work with, I had to recreate them but as they were included they were deleted on the same day or the next.

Since the existing template takes 3 days, I'll add 4 more and see what happens. I tell you

**Comment by leggett** [comment] 2021-01-03 17:06
I don't think it is possible that Simplify is deleting the templates (I don't even have API access)... I was assuming they just couldn't be accessed in the menu when Simplify is on. 

If you disable Simplify, are they still missing? If so, it might be something unrelated to Simplify.

**Comment by CarlosRebolledo** [comment] 2021-01-03 17:12
If I disable Simplify it doesn't solve it.  I'll tell you how I'm doing with the new templates that I added a few minutes ago and I'll see if it's another extension

**Comment by leggett** [comment] 2021-01-03 18:04
I can't reproduce any issues with templates on my end and I've had 7 for a long time.  

I'm going to close this issue for now but re-open it if you think it is Simplify.

**Closed by leggett** 2021-01-03 18:04 UTC
