### ISSUE TITLE
Since today, gmail changes broke Simplify Gmail

### ISSUE THREAD

**Issue by guilala** [leggett/simplify#168] opened 2019-05-16 08:02 UTC
Simplify Gmail extension seems to be broken today. Since there is no new version of the extension it must be due to changes in Gmail itself? See screenshot.

![brokenSimpleGmail](https://user-images.githubusercontent.com/108651/57836715-9d1fa100-77c1-11e9-80bd-f3cf395d1636.png)

**Comment by brhahlen** [comment] 2019-05-16 08:32
I am facing the same problem

**Comment by dulex123** [comment] 2019-05-16 08:46
Me too

**Comment by methodik** [comment] 2019-05-16 08:49
Me too

Video of what I'm seeing:
https://www.loom.com/share/860e8f4b7c2c4de39c70cb3c7a0bfa46

**Comment by syabro** [comment] 2019-05-16 09:04
same here
![image](https://user-images.githubusercontent.com/29029/57841150-b67d1900-77d2-11e9-8d5e-2270c114d32c.png)

**Comment by ukslim** [comment] 2019-05-16 09:31
Mine looks OK, but clicking "inbox" while a mail item is open, doesn't take me back the the message list, as of today. I assume this is also because of changes to Gmail today, so I won't raise it as a separate issue.

**Comment by loretoparisi** [comment] 2019-05-16 09:56
I'm facing the same issue. The problem is that there is an additional padding on top, so I cannot see anymore the search bar and click on the Inbox in the side bar.

**Comment by vicmortelmans** [comment] 2019-05-16 10:48
I have the same issue. And moreover, when I click the icon in the Chrome toolbar, to "temporary disable Simplify", the problem isn't completely fixed. Most hidden GUI-elements do reappear, but e.g. not the entry field for search. I must disable the extension completely to get search back.

**Comment by leggett** [comment] 2019-05-16 13:47
fix coming. duplicate of #167

**Closed by leggett** 2019-05-16 13:47 UTC

**Comment by guilala** [comment] 2019-05-17 09:03
Fixed! Thank you! :-) ...
