### ISSUE TITLE
App menu and FAB are hidden

### ISSUE THREAD

**Issue by raess** [leggett/simplify#406] opened 2020-10-04 19:40 UTC
The app menu as shown [here](https://cdn.substack.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Fc4f4697e-2e5b-48c9-ac3e-b1b65b4379ad_455x563.gif) and the FAB are hidden outside the screen. Both the app menu and the FAB start to appear at different widths of the window (e.g. 1040px) but still not fully visible.

MacBook Pro 13" @ 1440px
Chrome 85.0.4183.121

![Screen Recording 2020-10-04 at 21 31 13](https://user-images.githubusercontent.com/1557805/95025376-439f6700-0681-11eb-8b94-f1c9da5ec182.gif)

**Comment by leggett** [comment] 2020-10-04 19:54
Yeah, again, something is really weird here where you have part of Gmail outside of the viewable window. I can't reproduce this (I've tried making my window smaller, zooming, etc). I'm going to close this issue and track it on the one about chat being off the screen.

**Closed by leggett** 2020-10-04 19:54 UTC
