### ISSUE TITLE
Blinks and wide about 50% of screen

### ISSUE THREAD

**Issue by miesismore** [leggett/simplify#284] opened 2020-06-21 20:05 UTC
Don't know if this is since Gmail last changes to choose new UI settings but i'm getting continuos blinks and have the interface of messages about at 50% of normal....

**Comment by leggett** [comment] 2020-06-21 20:55
That sounds pretty strange! 

Do you have any other extensions that modify Gmail?

Can you post here or email me (at hi@simpl.fyi) a screenshot or a short screen capture video?

**Comment by leggett** [comment] 2020-06-21 20:58
I added support for the new Gmail settings a couple weeks ago. Maybe I broke something in the process?

When you say "blinks" do you mean the interface flickers? When does it do this? Between views (like when opening a message) or just at rest?

**Comment by leggett** [comment] 2020-06-27 02:37
Thanks for sending me the gif of the problem. Super strange! I'm not able to reproduce the issue on any of my accounts. It might be you have some kind of experimental feature. I'm going to close this issue for now but please re-open it if you see it on multiple accounts.

**Closed by leggett** 2020-06-27 02:37 UTC
