### ISSUE TITLE
Dark theme + new logo + gmail loading screen = bad look

### ISSUE THREAD

**Issue by quickdraw-m** [leggett/simplify#414] opened 2020-10-23 16:36 UTC
![Screenshot 2020-10-23 at 12 33 04 - Edited](https://user-images.githubusercontent.com/70546828/97029953-1f220680-152c-11eb-9b3d-675f9c534cc1.png)

I have mixed feelings on this new Gmail logo/icon at all, but I think we can agree this particularly isn't looking great.  Not sure how I'd go about fixing it, though.

**Comment by leggett** [comment] 2020-10-23 23:37
Yeah... that doesn't look so hot. Part of the problem is Gmail is loading before the animation even starts. I'm going to try and hide the top triangle so it at least it looks like an M.

**Comment by leggett** [comment] 2020-10-24 00:00
Just for the dark theme...
![loading](https://user-images.githubusercontent.com/8763662/97062781-43dca500-1551-11eb-9454-967a2d46238d.gif)

**Comment by quickdraw-m** [comment] 2020-10-24 00:14
Oh that is _hot_

**Comment by leggett** [comment] 2020-10-24 00:29
I'm going to close this -- will go out with next update (v2.1.14)

**Closed by leggett** 2020-10-24 00:29 UTC
