### ISSUE TITLE
[feedback] expand message to full width in horizontal reading pane

### ISSUE THREAD

**Issue by derylseale** [leggett/simplify#321] opened 2020-08-31 19:05 UTC
This might just be a personal (and boring) preference, but when using the horizontal reading pane with the the default theme in v2, there is decent amount wasted space. I can see how with a background image it's more visually interesting, but with the default theme is just more gray than I'd like to see. Also in this case, I'd like the message menu bar above the message to match the menu bar above the message list (i.e. white).

<img width="662" alt="Screen Shot 2020-08-31 at 2 53 21 PM" src="https://user-images.githubusercontent.com/1426718/91756711-2c112200-eb9b-11ea-9520-941d4d158b9d.png">

Below is a crude mockup of what I was sort of expecting to see (note I wasn't able to make the menu bar background white).

<img width="881" alt="Screen Shot 2020-08-31 at 3 17 30 PM" src="https://user-images.githubusercontent.com/1426718/91757954-2fa5a880-eb9d-11ea-8ba2-0dd85b16d722.png">

**Comment by leggett** [comment] 2020-08-31 21:54
Thanks for the report. I originally had it all white (because I hadn't done this extra work) and it felt like a bad experience to me. 
 So, this is largely working as intended but I'll spell out why and would love to hear if you have additional thoughts.

 - This is a special case in the default theme (which is all white)
 - Since I am making the message list all white (or all black in the dark theme), there is poor contrast / grouping of information as everything is on white. It all just blurs together. 
 - As a result, in this case (the default all white theme), I add a light gray background behind the message side of the app to help group the actions and conversation all together and set them apart from the message list.

I could try instead to put a background behind the message list in this one case but it is a lot harder as there are potentially a lot of different elements / components in the message list and the nav itself. But it may be possible.

**Comment by leggett** [comment] 2020-08-31 22:01
The top margin is there in all setups and all views so the conversation doesn't feel so cramped up against the top bar. 

<img width="1680" alt="Screen Shot 2020-08-31 at 2 57 13 PM" src="https://user-images.githubusercontent.com/8763662/91772952-b0af7080-eb9a-11ea-86c8-593af09bfb33.png">

But not everyone is using a large display or has their nav minimized such that there is a lot of space around the message. And when the space for the message is small such that there is almost no margin on either side of the conversation any more (as it is in your screenshot), I agree that it looks weird. 

I might be able to detect when that happens and remove the top margin.

**Comment by derylseale** [comment] 2020-08-31 23:56
In my case, I have email in a smaller browser window on another monitor, as it's secondary to my primary workspace. I have no idea if that's common, but I can definitely see how correcting for the case of a smaller window may make things differently worse for large displays. I gather that that kind of responsiveness is difficult to achieve.

I also take your point on the abundance of white. To my eyes, everything still looks distinct with no background, but that's just one opinion. Maybe making the borders between top/bottom and right/left a little thicker or darker might help?

**Comment by derylseale** [comment] 2020-09-03 15:06
Having lived with this a few days, the only thing really stands out to me now is the top margin. I think if the message preview was top aligned with the first item in the message list on the left, it would look better (in my opinion). But I'm don't know if that's easy to do reliably across many different use cases.

<img width="620" alt="Screen Shot 2020-09-03 at 11 01 56 AM" src="https://user-images.githubusercontent.com/1426718/92132741-8a294980-edd5-11ea-97a7-6ac1091cb071.png">

**Comment by leggett** [comment] 2020-10-05 19:33
In v2.1.12, I got rid of the top margin when the reading pane is narrow as you have it (and there isn't much padding on the sides of the message). Closing this issue for now. Thanks again for all the feedback/screenshots.

**Closed by leggett** 2020-10-05 19:33 UTC
