### ISSUE TITLE
Maybe a new toolbar icon breaks layout overlap Settings icon

### ISSUE THREAD

**Issue by dany-eudes** [leggett/simplify#197] opened 2019-06-27 19:52 UTC
I noted today, after a Google Chrome update,  that a Support icon appears on the side of Google Account icon. Unfortunately, I think this breaks the toolbar layout again.

See the image.

Chrome Version 75.0.3770.100 (oficial version) 64 bits / Windows 10
![image](https://user-images.githubusercontent.com/82278/60290550-5e682500-98ef-11e9-8b39-6c95d1986b31.png)

**Comment by leggett** [comment] 2019-06-27 20:23
Thanks for the report and screenshot.

I believe this is fixed in v1.5.9 which I submitted last Sunday and has been in some special review since.  

It may also be fixed in v1.5.8. Can you try restarting Chrome and seeing if it persists?

**Comment by dany-eudes** [comment] 2019-06-27 21:33
Now, these screenshots are from Simplify Gmail v1.5.8. It's Ok now as you can see. Thank you so much for your amazing work.

Normal state.
![image](https://user-images.githubusercontent.com/82278/60301937-eb6ba800-9908-11e9-8ce9-46f59241fcc6.png)

When pointer is over Google Account Icon.
![image](https://user-images.githubusercontent.com/82278/60302005-2077fa80-9909-11e9-895e-d60dab295b9b.png)

**Comment by leggett** [comment] 2019-06-27 23:33
Hmm... that looks quite broken. I'll look into it. I'm on vacation this week so may not be until early next week.

**Comment by leggett** [comment] 2019-06-27 23:52
Hmm... that looks quite broken. I'll look into it. I'm on vacation this week so may not be until early next week.

**Comment by leggett** [comment] 2019-07-02 01:04
Looking at this a bit more and some of this is still mysterious to me. 

**Some initial observations:**

- One of the problems here is the Support button isn't being hidden.
- Starting with v1.3.6, I detect the classnames for items that frequently get different classnames (including the Support button). So even though the classname changed, Simplify should still detect the correct classname and hide it.
- It appears that the Support button (and perhaps other items) load in a bit later than I expect when Mailtrack (and probably other 3rd party extensions) is installed. So, it appears that when Simplify goes to detect the classname for the Support button, it isn't actually in the DOM yet. :/
- I'm going to wait longer before detecting updated classnames in v1.6.0 to cover this case. Not perfect but should do the trick.

**What happened to v1.5.9?**

- I'm still waiting for Google to approve the v1.5.9 update I posted over a week ago that changes the default classname for the Support button and other items (which I fall back to when I can't find the element). Not sure what is taking so long... but they told me it shouldn't take more than 7 days (I assume business days) so it should update this week and subsequent updates should go back to ~1 hour to publish.

**The things I see broken here that I can't reproduce:**

- When you have any of the 3rd party extensions I try to support (such as Mailtrack), hovering over the profile image should hide the search bar entirely, not just move it over as you show in your screenshots. Not sure why that isn't working and I can't reproduce it. Below is what I see running v1.5.8 with Mailtrack added.
- The action bar (select, refresh, preview pane settings, etc) should all be in the top bar as they were in your first screenshot AND they should line up with the inbox. See below screenshots.

<img width="1532" alt="Screen Shot 2019-07-01 at 5 59 45 PM" src="https://user-images.githubusercontent.com/8763662/60475086-62b37b80-9c2a-11e9-9aa8-1760ce2c63c3.png">
<img width="1533" alt="Screen Shot 2019-07-01 at 5 59 55 PM" src="https://user-images.githubusercontent.com/8763662/60475094-6810c600-9c2a-11e9-8541-11dc7622424b.png">

I can't recreate what you have in your screenshots with v1.5.8. Maybe you have another 3rd party extension running... If not, I'm not sure what is going on.

**Comment by leggett** [comment] 2019-07-07 16:26
I've made some considerable changes to how the search box works adding a 3rd state (open but not focused) that is smaller while making the focused state much bigger and hiding the buttons to the left of the search box. As soon as Google unblocks updates (I haven't been able to update Simplify for 2 weeks), I'll get it out.

**Closed by leggett** 2019-07-07 16:26 UTC
